(function(){var aa;function ba(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function p(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:ba(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function ca(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}function da(a){return a instanceof Array?a:ca(p(a))}
var ea="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},fa;if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa,la={construct:"Metrika2",callbackPostfix:"2",version:"3brkhoacvw3mwaouhgtqp4q1skk2",host:"mc.yandex.ru"};
function ma(a,b){return b(a)}function q(a){return function(b){return function(c){return a(b,c)}}}function na(a){return function(b){return function(c){return a(c,b)}}}var pa=q(function(a,b){return a===b}),qa=q(function(a,b){a(b);return b}),ra=q(ma);function t(){}var sa=[];
function ta(a,b){if(!b||"function"!==typeof b)return!1;try{var c=""+b}catch(h){return!1}var d=c.length;if(d>35+a.length)return!1;for(var e=d-13,f=0,g=8;g<d;g+=1){f="[native code]"[f]===c[g]||7===f&&"-"===c[g]?f+1:0;if(12===f)return!0;if(!f&&g>e)break}return!1}function ua(a,b){var c=ta(a,b);b&&!c&&sa.push([a,b]);return c}function va(a,b){return ua(b,a)&&a}function wa(a,b){for(var c=0;c<b.length;c+=1)if(b[c]===a)return c;return-1}var xa;
function za(a){if(xa)return xa;var b=!1;try{b=[].indexOf&&0===[void 0].indexOf(void 0)}catch(d){}var c=a.Array&&a.Array.prototype&&va(a.Array.prototype.indexOf,"indexOf");return xa=a=b&&c?function(d,e){return c.call(e,d)}:wa}var Aa=za(window),Ba=na(Aa);function v(a){return a}function Ca(a,b){return b}function Da(a){return!a}var Ea=va(Array.from,"from");function Fa(a){for(var b=a.length,c=[],d=0;d<b;d+=1)c.push(a[d]);return c}function Ga(a){if(Ea)try{return Ea(a)}catch(b){}return Fa(a)}
function w(a,b){var c=[],d=[];var e=b?b:v;return function(){var f=Ga(arguments),g=e.apply(null,da(f)),h=Aa(g,d);if(-1!==h)return c[h];f=a.apply(null,da(f));c.push(f);d.push(g);return f}}var Ha=/\./g;function Ia(a){return"string"===typeof a}var Ja=va(String.prototype.indexOf,"indexOf");function Ka(a,b){for(var c=0,d=a.length-b.length,e=0;e<a.length;e+=1){c=a[e]===b[c]?c+1:0;if(c===b.length)return e-b.length+1;if(!c&&e>d)break}return-1}var La=Ja?function(a,b){return Ja.call(a,b)}:Ka;
function Ma(a,b){return La(a,b)}function Na(a,b){return!(!a||-1===La(a,b))}function Oa(a){return a.replace(/\^/g,"\\^").replace(/\$/g,"\\$").replace(Ha,"\\.").replace(/\[/g,"\\[").replace(/\]/g,"\\]").replace(/\|/g,"\\|").replace(/\(/g,"\\(").replace(/\)/g,"\\)").replace(/\?/g,"\\?").replace(/\*/g,"\\*").replace(/\+/g,"\\+").replace(/\{/g,"\\{").replace(/\}/g,"\\}")}var Pa=pa(null);function x(a){return"function"===typeof a}var z=pa(void 0);function Qa(a){return z(a)||Pa(a)}
function Ra(a){return!Pa(a)&&!z(a)&&"[object Object]"===Object.prototype.toString.call(a)}function Sa(a,b,c){b=void 0===b?[]:b;c=c||{};var d=b.length,e=a;x(e)&&(e="d",c[e]=a);var f;d?1===d?f=c[e](b[0]):2===d?f=c[e](b[0],b[1]):3===d?f=c[e](b[0],b[1],b[2]):4===d&&(f=c[e](b[0],b[1],b[2],b[3])):f=c[e]();return f}var Ta=va(Function.prototype.bind,"bind");
function Ua(){var a=Ga(arguments);a=p(a);var b=a.next().value,c=a.next().value,d=ca(a);return function(){var e=[].concat(da(d),da(Ga(arguments)));if(Function.prototype.call)return Function.prototype.call.apply(b,[c].concat(da(e)));if(c){for(var f="_b";c[f];)f+="_"+f.length;c[f]=b;e=c[f]&&Sa(f,e,c);delete c[f];return e}return Sa(b,e)}}var Va=Ta?function(){var a=Ga(arguments),b=p(a);a=b.next().value;var c=b.next().value;b=ca(b);return Ta.apply(a,[c].concat(b))}:Ua;
function B(a,b){return Va.apply(null,[b,null].concat(da(a)))}function C(a,b){return Va(b,null,a)}function Wa(a,b){return Va(b[a],b)}function Xa(a){return Wa("test",a)}var Ya=va(Array.prototype.reduce,"reduce");function Za(a,b,c){for(var d=0,e=c.length;d<e;)b=a(b,c[d],d),d+=1;return b}var E=Ya?function(a,b,c){return Ya.call(c,a,b)}:Za;function $a(a,b){return B([a,b],E)}function F(){var a=Ga(arguments),b=a.shift();return function(){var c=b.apply(null,arguments);return E(ma,c,a)}}
var ab=q(B),bb=q(Wa),cb=Object.prototype.hasOwnProperty;function db(a,b){return Qa(a)?!1:cb.call(a,b)}function G(a,b){return a?E(function(c,d){if(Qa(c))return c;try{return c[d]}catch(e){}return null},a,b.split(".")):null}var I=na(G),eb=I("length");function fb(a){var b=void 0===b?{}:b;if(!a||1>a.length)return b;E(function(c,d,e){if(e===a.length-1)return c;e===a.length-2?c[d]=a[e+1]:db(c,d)||(c[d]={});return c[d]},b,a);return b}
function gb(a,b){var c=G(b,a),d=G(b,"constructor.prototype."+a)||c;try{if(d&&d.apply)return function(){return d.apply(b,arguments)}}catch(e){return c}return d}function hb(a,b,c){return c?a:b}var ib=B([1,null],hb),jb=B([1,0],hb),kb=Boolean,lb=va(Array.prototype.filter,"filter");function mb(a,b){return Za(function(c,d,e){a(d,e)&&c.push(d);return c},[],b)}var nb=lb?function(a,b){return lb.call(b,a)}:mb,ob=C(kb,nb),pb=q(nb);function J(a,b,c){return Array.prototype.includes.call(b,a,c)}var qb=na(J);
function rb(a){return"[object Array]"===Object.prototype.toString.call(a)}var sb=va(Array.isArray,"isArray"),tb=sb?function(a){return sb(a)}:rb;function ub(a){return a?tb(a)?a:Ea?Ea(a):"number"===typeof a.length&&0<=a.length?Fa(a):[]:[]}var vb=w(za),wb=I("0");function xb(a){return a.splice(0,a.length)}
var yb=w(function(a){var b=G(a,"navigator")||{};a=G(b,"userAgent")||"";b=G(b,"vendor")||"";return{wb:-1<La(b,"Apple"),Yb:a}}),zb=w(I("navigator.userAgent")),Ab=/Firefox\/([0-9]+)/i,Bb=w(function(a){var b=G(a,"document.documentElement.style"),c=G(a,"InstallTrigger");a=-1!==(G(a,"navigator.userAgent")||"").toLowerCase().search(Ab);Ab.lastIndex=0;return!(!(b&&"MozAppearance"in b)||Qa(c))||a});
function Cb(){var a=Array.prototype.map;if(!Bb(window))return!0;try{a.call({0:!0,length:-Math.pow(2,32)+1},function(){throw 1;})}catch(b){return!1}return!0}var Db=va(Array.prototype.map,"map");function Eb(a,b){return E(function(c,d,e){c.push(a(d,e));return c},[],b)}var K=Db&&Cb()?function(a,b){return b&&0<b.length?Db.call(b,a):[]}:Eb,Fb=q(K),Gb=na(K),Hb=va(Array.prototype.some,"some");function Ib(a,b){for(var c=0;c<b.length;c+=1)if(c in b&&a.call(b,b[c],c))return!0;return!1}
var Jb=Hb?function(a,b){return Hb.call(b,a)}:Ib;function Kb(a){try{return parseInt(a,10)}catch(b){return null}}var Lb=na(parseInt),Mb=Lb(10),Nb=Lb(2),Ob=va(Object.keys,"keys");function Pb(a){var b=[],c;for(c in a)db(a,c)&&b.push(c);return b}
var Qb=function(a){return function(b){return b?a(b):[]}}(Object.entries),L=Ob?function(a){return Ob(a)}:Pb,M=Object.assign,Rb=q(function(a,b){return M({},a,b)}),Sb=w(F(I("String.fromCharCode"),C("fromCharCode",ua),Da)),Tb=w(F(zb,Xa(/ipad|iphone|ipod/i))),Ub=w(function(a){return G(a,"navigator.platform")||""}),Wb=w(function(a){a=yb(a);var b=a.Yb;return a.wb&&!b.match("CriOS")}),Xb=Xa(/Android.*Version\/[0-9][0-9.]*\sChrome\/[0-9][0-9.]|Android.*Version\/[0-9][0-9.]*\s(?:Mobile\s)?Safari\/[0-9][0-9.]*\sChrome\/[0-9][0-9.]*|; wv\).*Chrome\/[0-9][0-9.]*\sMobile/),
Yb=Xa(/; wv\)/),Zb=w(function(a){a=zb(a);return Yb(a)||Xb(a)}),$b=w(function(a){a=(zb(a)||"").toLowerCase();return Na(a,"android")&&Na(a,"mobile")}),ac="other none unknown wifi ethernet bluetooth cellular wimax mixed".split(" "),bc=w(function(a){var b=G(a,"navigator.connection.type");if(z(b))return null;a=vb(a)(b,ac);return-1===a?b:""+a}),cc=w(F(I("document.addEventListener"),Da)),dc=w(function(a){var b=G(a,"navigator")||{};return E(function(c,d){return c||G(b,d)},"",["language","userLanguage","browserLanguage",
"systemLanguage"])}),ec=w(function(a){var b=G(a,"navigator")||{};a=dc(a);Ia(a)||(a="",b=G(b,"languages.0"),Ia(b)&&(a=b));return a.toLowerCase().split("-")[0]}),fc=w(function(a){return(G(a,"top")||a)!==a}),gc=w(I("top.contentWindow")),hc=w(function(a){var b=!1;try{b=a.navigator.javaEnabled()}catch(c){}return b});function ic(a){return J("prerender",K(C(G(a,"document"),G),["webkitVisibilityState","visibilityState"]))}
var jc=w(function(a){var b=zb(a)||"",c=b.match(/Mac OS X ([0-9]+)_([0-9]+)/);c=c?[+c[1],+c[2]]:[0,0];b=b.match(/iPhone OS ([1-9]+)_([0-9]+)/);return 14<=(b?+b[1]:0)?!0:(Tb(a)||10<c[0]||10===c[0]&&13<=c[1])&&Wb(a)}),kc=/Edg\/(\d+)\./,lc=w(function(a){var b;if(!(b=jc(a)))a:{if(Bb(a)&&(b=zb(a).match(Ab))&&b.length){b=68<=+b[1];break a}b=!1}if(!b)a:{if((a=zb(a))&&(a=a.match(kc))&&1<a.length){b=79<=Mb(a[1]);break a}b=!1}return b}),mc=la.construct,nc=la.host,oc=cc(window),N={hc:24226447,bc:26302566,jc:51533966,
ed:65446441,fa:"https:",ea:"2012",nc:mc,fc:oc?512:2048,dc:oc?512:2048,ec:oc?100:400,fd:100,ic:"noindex"},pc=pa("1");function qc(a,b,c,d){var e={};return Ra(a)?a:(e.id=a,e.type=c,e.defer=d,e.params=b,e)}function rc(a){return E(function(b,c){var d=p(c),e=d.next().value,f=d.next().value;d=f.bb;f=a[f.X];b[e]=d?d(f):f;return b},{},Qb(sc))}var O=w(function(a){return a.id+":"+a.L});
function tc(a){a=a.Ya=a.Ya||{};var b=a._metrika=a._metrika||{};return{O:function(c,d){db(b,c)||(b[c]=d);return this},A:function(c,d){b[c]=d;return this},m:function(c,d){var e=b[c];return db(b,c)||z(d)?e:d}}}var P=w(tc),Q=window.Promise,uc=["http.0.st..rt.","network error occurred","send beacon","Content Security Policy","DOM Exception 18"],vc;function wc(a){this.message=a}
var xc=function(a){return function(b,c){c=void 0===c?!1:c;if(vc)var d=new vc(b);else ua("Error",a.Error)?(vc=a.Error,d=new a.Error(b)):(vc=wc,d=new vc(b));c&&(d.unk=!0);return d}}(window),yc=Xa(RegExp("^http."));function zc(a){throw a;}function Ac(a,b){for(var c="",d=0;d<b.length;d+=1)c+=""+(d?a:"")+b[d];return c}
var Bc=va(Array.prototype.join,"join"),S=Bc?function(a,b){return Bc.call(b,a)}:Ac,Cc=q(S),Dc=w(function(a){a=!(!a.addEventListener||!a.removeEventListener);return{Qc:a,C:a?"addEventListener":"attachEvent",Ha:a?"removeEventListener":"detachEvent"}});function Ec(a,b,c,d,e,f){a=Dc(a);var g=a.C,h=a.Ha;f=f?h:g;if(b[f])if(a.Qc)if(e)b[f](c,d,e);else b[f](c,d);else b[f]("on"+c,d)}
var Fc=w(function(a){var b=!1;if(!a.addEventListener)return b;try{var c=Object.defineProperty({},"passive",{get:function(){b=!0;return 1}});a.addEventListener("test",t,c)}catch(d){}return b}),Gc=q(function(a,b){if(null!==b)return a?M({capture:!0,passive:!0},b||{}):!!b}),Hc=w(function(a){var b=Fc(a),c=Gc(b),d={};return M(d,{C:function(e,f,g,h){K(function(k){var l=c(h);Ec(a,e,k,g,l,!1)},f);return Va(d.xa,d,e,f,g,h)},xa:function(e,f,g,h){K(function(k){var l=c(h);Ec(a,e,k,g,l,!0)},f)}})});
function Ic(a){return G(a,"performance")||G(a,"webkitPerformance")}function Jc(a){a=Ic(a);var b=G(a,"timing.navigationStart"),c=G(a,"now");c&&(c=Va(c,a));return[b,c]}function Kc(a,b){var c=p(b||Jc(a)),d=c.next().value;c=c.next().value;return!isNaN(d)&&x(c)?Math.round(c()+d):a.Date.now?a.Date.now():(new a.Date).getTime()}function Lc(a){return(10>a?"0":"")+a}
function Mc(a){var b=Hc(a),c=Jc(a),d={l:a,jb:0,T:c,yc:Kc(a,c)},e=p(c);c=e.next().value;e=e.next().value;c&&e||b.C(a,["beforeunload","unload"],function(){0===d.jb&&(d.jb=Kc(a,d.T))});return ra(d)}function T(a){var b=a.jb;return 0!==b?b:Kc(a.l,a.T)}function Nc(a){return Math.floor(T(a)/1E3/60)}function Oc(a){return Math.round(T(a)/1E3)}function Pc(a){var b=p(a.T),c=b.next().value;b=b.next().value;a=c&&b?b():T(a)-a.yc;return Math.round(a)}var U=w(Mc);function Qc(a){return a.hb||a.Ea.length<=a.R}
function Rc(a){a.R=a.Ea.length}function Sc(a){a.hb=!0}function Tc(a){a.hb=!1}function Uc(a){Qc(a)&&zc(xc("i"));var b=a.zb(a.Ea[a.R]);a.R+=1;return b}var Vc=q(function(a,b){for(var c=[];!Qc(b);){var d=Uc(b);a(d,function(e){return e(b)});c.push(d)}return c});function Wc(a,b){return function(c){var d=U(a),e=d(T);return Vc(function(f,g){d(T)-e>=b&&g(Sc)})(c)}}
function Xc(a){for(var b=!0,c={};!Qc(a)&&b;c={ab:void 0})b=!1,c.ab=function(){b=!0;a.R+=1},a.zb(a.Ea[a.R],function(d){return function(){(0,d.ab)()}}(c)),b||(a.R+=1,c.ab=C(a,Xc))}function Yc(a,b){return ra({Ea:a,zb:b||v,hb:!1,R:0})}function Zc(a,b,c){c=void 0===c?!1:c;return new Q(function(d,e){function f(k,l){l();d()}var g=a.slice();g.push({H:f,da:f});var h=Yc(g,function(k,l){var m=c?k.H:k.da;if(m)try{m(b,l)}catch(n){h(Rc),e(n)}else l()});h(Xc)})}
function $c(a){try{return encodeURIComponent(a)}catch(b){}a=S("",nb(function(b){return 55296>=b.charCodeAt(0)},a.split("")));return encodeURIComponent(a)}function ad(a){var b="";try{b=decodeURIComponent(a)}catch(c){}return b}function bd(a){return a?F(Fb(function(b){var c=p(b.split("="));b=c.next().value;c=c.next().value;return[b,Qa(c)?void 0:ad(c)]}),$a(function(b,c){var d=p(c),e=d.next().value;d=d.next().value;b[e]=d;return b},{}))(a.split("&")):{}}
function cd(a){return a?F(Qb,$a(function(b,c){var d=p(c),e=d.next().value;d=d.next().value;z(d)||Qa(d)||b.push(e+"="+$c(d));return b},[]),Cc("&"))(a):""}function dd(a,b,c){var d=z(c);z(b)&&d?(d=1,b=1073741824):d?d=1:(d=b,b=c);return a.Math.floor(a.Math.random()*(b-d))+d}function ed(a,b,c){return function(){var d=P(arguments[0]),e=c?"global":"m2012",f=d.m(e,{}),g=G(f,a);g||(g=w(b),f[a]=g,d.A(e,f));return g.apply(null,arguments)}}var fd=qb([26812653]),gd=w(F(I("id"),fd),O),hd="hash host hostname href pathname port protocol search".split(" ");
function V(a){return E(function(b,c){var d=G(a,"location."+c);b[c]=d?""+d:"";return b},{},hd)}var id="ru by kz az kg lv md tj tm uz ee fr lt com co.il com.ge com.am com.tr com.ru".split(" "),jd=/(?:^|\.)(?:(ya\.ru)|(?:yandex)\.(\w+|com?\.\w+))$/,kd=w(function(a){return(a?a.replace(/^www\./,""):"").toLowerCase()}),ld=w(function(a){a=V(a).hostname;var b=!1;a&&(b=-1!==a.search(jd));return b}),md=/^\s+|\s+$/g,nd=va(String.prototype.trim,"trim");
function od(a){return a?nd?nd.call(a):(""+a).replace(md,""):""}var pd=q(function(a,b){return b.replace(a,"")})(/\D/g),qd=["metrika_enabled"],rd=[];function sd(a,b){var c=td;return!rd.length||J(b,qd)?!0:E(function(d,e){return d&&e(a,c,b)},!0,rd)}function ud(a){try{var b=a.document.cookie;if(!Qa(b)){var c={};K(function(d){var e=p(d.split("="));d=e.next().value;e=e.next().value;c[od(d)]=od(ad(e))},(b||"").split(";"));return c}}catch(d){}return null}var vd=ed("gsc",ud);
function td(a,b){var c=vd(a);return c?c[b]||null:null}var wd=/:\d+$/;function xd(a,b,c,d,e,f,g){g=void 0===g?!1:g;if(sd(a,b)){var h=b+"="+encodeURIComponent(c)+";";if(d){var k=new Date;k.setTime(k.getTime()+6E4*d);h+="expires="+k.toUTCString()+";"}e&&(d=e.replace(wd,""),h+="domain="+d+";");try{a.document.cookie=h+("path="+(f||"/")),g||(vd(a)[b]=c)}catch(l){}}}
var yd=w(function(a){var b=(V(a).host||"").split(".");return 1===b.length?b[0]:E(function(c,d,e){e+=1;2<=e&&!c&&(e=S(".",b.slice(-e)),xd(a,"metrika_enabled","1",0,e,void 0,!0),(d=(d=ud(a))&&d.metrika_enabled)&&xd(a,"metrika_enabled","",-100,e,void 0,!0),d&&(c=e));return c},"",b)});
function zd(a,b,c){b=void 0===b?"_ym_":b;c=void 0===c?"":c;var d=yd(a),e=1===(d||"").split(".").length?d:"."+d,f=c?"_"+c:"";return{Aa:function(g,h,k){xd(a,""+b+g+f,"",-100,h||e,k,!1);return this},m:function(g){return td(a,""+b+g+f)},A:function(g,h,k,l,m){xd(a,""+b+g+f,h,k,l||e,m);return this}}}
var Ad=w(zd),Bd=w(function(a){var b=Ad(a),c="1"===b.m("debug"),d=-1<Ma(V(a).href,"_ym_debug=1")||-1<Ma(V(a).href,"_ym_debug=2"),e=a._ym_debug;!e&&!d||c||(a=V(a),b.A("debug","1",void 0,a.host));return!!(c||e||d)});function Cd(){return{}}function Dd(){return[]}var Ed=ed("debuggerEvents",Dd,!0);function Fd(a,b){if(Bd(a)){var c=b.counterKey;if(c){var d=p(c.split(":"));c=d.next().value;d=d.next().value;c=fd(Kb(c));if("1"===d||c)return}c=Ed(a);1E3===c.length&&c.shift();c.push(b)}}
function Gd(a,b,c){var d=dd(a),e=c.aa,f=c.K,g=c.ma,h=c.Ja;c=c.lb;var k={},l={},m={};Fd(a,(m.name="request",m.data=(l.url=b,l.requestId=d,l.senderParams=(k.rBody=f,k.debugStack=e,k.rHeaders=g,k.rQuery=h,k.verb=c,k),l),m));return d}function Hd(a,b){return Array.prototype.find.call(b,a)}
var Id=q(function(a,b){var c=b||{};return{l:C(c,v),m:function(d,e){var f=c[d];return z(f)&&!z(e)?e:f},A:function(d,e){c[d]=e;return this},gb:function(d,e){return""===e||Qa(e)?this:this.A(d,e)},Ma:C(c,a)}}),Jd=Id(function(a){var b="";a=E(function(c,d){var e=p(d),f=e.next().value;e=e.next().value;e=""+f+":"+e;"t"===f?b=e:c.push(e);return c},[],Qb(a));b&&a.push(b);return S(":",a)});
function Kd(a,b,c){var d=M({},b.B);a=U(a);b.D&&(d["browser-info"]=Jd(b.D.l()).A("st",a(Oc)).Ma());!d.t&&(b=b.V)&&(b.A("ti",c),d.t=b.Ma());return d}
function Ld(a,b,c,d,e,f){e=void 0===e?0:e;f=void 0===f?0:f;var g=M({aa:[]},d.I),h=p(b[f]),k=h.next().value;h=h.next().value;var l=c[e];if((!g.ma||!g.ma["Content-Type"])&&g.K){var m={};g.ma=M({},g.ma,(m["Content-Type"]="application/x-www-form-urlencoded",m));g.K="site-info="+$c(g.K)}g.lb=g.K?"POST":"GET";g.Ja=Kd(a,d,k);g.U=(d.$||{}).U;g.aa.push(k);M(d.I,g);k=""+l+(d.Ia&&d.Ia.Fc?"/1":"");var n=0;n=Gd(a,k,g);return h(k,g).then(function(u){var r=n,y={},A={};Fd(a,(A.name="requestSuccess",A.data=(y.body=
u,y.requestId=r,y),A));return{Jb:u,Xb:e}})["catch"](function(u){var r=n,y={},A={};Fd(a,(A.name="requestFail",A.data=(y.error=u,y.requestId=r,y),A));r=f+1>=b.length;y=e+1>=c.length;r&&y&&zc(u);return Ld(a,b,c,d,!y&&r?e+1:e,r?0:f+1)})}function Md(a,b){return function(c,d){return Ld(a,b,d,c)}}function Nd(a,b){K(F(v,Wa("push",a)),b);return a}function Od(a,b){return b?a(b):a()}
var Pd=F(v,Od),Rd={id:"id",$b:"ut",L:"type",Za:"ldc",Fa:"nck",Sa:"url",vc:"referrer"},Sd=/^\d+$/,Td={id:function(a){a=""+(a||"0");Sd.test(a)||(a="0");try{var b=Mb(a)}catch(c){b=0}return b},L:function(a){return""+(a||0===a?a:"0")},Fa:kb,$b:kb};Rd.Oa="defer";Td.Oa=kb;Rd.G="params";Td.G=function(a){return Ra(a)||tb(a)?a:null};Rd.Vb="trackLinks";var sc=E(function(a,b){var c=p(b),d=c.next().value;c=c.next().value;a[d]={X:c,bb:Td[d]};return a},{},Qb(Rd));
function Ud(a){return E(function(b,c){var d=p(c),e=d.next().value;d=d.next().value;b[sc[e].X]=d;return b},{},Qb(a))}function Vd(a,b,c){for(var d=[b,c],e=-1E4,f=0;f<a.length;f+=1){var g=p(a[f]),h=g.next().value;g=g.next().value;if(c===g&&h===b)return;if(c<g&&c>=e){a.splice(f,0,d);return}e=g}a.push(d)}
var Wd={},Xd=(Wd.w=[[function(a,b){return{H:function(c,d){var e=c.B,f={};e=(f["page-url"]=e&&e["page-url"]||"",f.charset="utf-8",f);"0"!==b.L&&(e["cnt-class"]=b.L);c.D||(c.D=Jd());f=c.D;e={$:{U:"watch/"+b.id},I:M(void 0===c.I?{}:c.I,{ac:!!f.m("pv")&&!f.m("ar")&&!f.m("wh")}),B:M(c.B||{},e)};M(c,e);d()}}},1]],Wd);
function Yd(a,b,c){var d=Md(a,b);return function(e){return Zc(c,e,!0).then(function(){var f=e.$||{},g=void 0===f.xc?"":f.xc,h=void 0===f.U?"":f.U;f=K(function(k){return N.fa+"//"+(""+g+k||nc)+"/"+h},void 0===f.ub?[nc]:f.ub);return d(e,f)}).then(function(f){var g=f.Jb;f=f.Xb;e.pd=g;e.qd=f;return Zc(c,e).then(C(g,v))})}}function Zd(a){return function(b,c,d){return function(e,f){var g=K(F(wb,ab([b,f]),Od),Xd[a]||[]);g=Nd(g,d);return Yd(b,c,g)(e)}}}var $d=Zd("w"),ae=["webkitvisibilitychange","visibilitychange"];
function be(a){return{H:function(b,c){var d=a.document,e=b.D;if(e&&ic(a)){var f=Hc(a),g=function(h){ic(a)||(f.xa(d,ae,g),c());return h};f.C(d,ae,g);e.A("pr","1")}else c()}}}function ce(a){var b="";tb(a)?b=S(".",a):Ia(a)&&(b=a);return xc("err.kn("+N.ea+")"+b)}function de(){var a=Ga(arguments);zc(ce(a))}var ee=Xa(RegExp("^err.kn")),fe=[];
function ge(a,b,c){var d="u.a.e",e="";c&&("object"===typeof c?(c.unk&&zc(c),d=c.message,e="string"===typeof c.stack&&c.stack.replace(/\n/g,"\\n")||"n.s.e.s"):d=""+c);ee(d)||Jb(C(d,Na),uc)||yc(d)&&.1<=a.Math.random()||K(F(v,ab(["jserrs",d,b,e]),Od),fe)}var he=0,ie=0,je=0;
function ke(a,b,c){return function(){he+=1;var d=null,e=null,f=Ic(c),g=f?ua("now",f.now):!1;try{var h=g?f.now():0;e=a.apply(null,arguments);var k=g?f.now():0;f=k-h;h=he>ie;300<=f&&h&&(ie=he,!g||k%1E3||K(F(v,ab(["perf","t.l.300",b,void 0]),Od),fe));1===he&&50<=f&&(je+=f)}catch(l){d=l}--he;he<ie&&(ie=he);d&&zc(d);return e}}function W(a,b,c,d){var e=c||zc;e=c?ke(e,b,a):e;return function(){var f=d;try{f=e.apply(null,arguments)}catch(g){ge(a,b,g)}return f}}
function X(a,b,c){return function(){return W(arguments[0],a,b,c).apply(this,arguments)}}var le=Id(function(a){a=Qb(a);return S("",K(function(b){var c=p(b);b=c.next().value;c=c.next().value;return Pa(c)?"":b+"("+c+")"},a))});function me(a,b,c){c=void 0===c?null:c;a.V||(a.V=le());b&&a.V.gb(b,c);return a.V}
var ne=[],oe=/^\s*(data|javascript):/i,pe=new RegExp(S("",["\\.("+S("|","3gp 7z aac ac3 acs ai avi ape apk asf bmp bz2 cab cdr crc32 css csv cue divx dmg djvu? doc(x|m|b)? emf eps exe flac? flv iso swf gif t?gz jpe?g? js m3u8? m4a mp(3|4|e?g?) m4v md5 mkv mov msi ods og(g|m|v) psd rar rss rtf sea sfv sit sha1 svg tar tif?f torrent ts txt vob wave? wma wmv wmf webm ppt(x|m|b)? xls(x|m|b)? pdf phps png xpi g?zip".split(" "))+")$"]),"i"),qe={},re=(qe.hit="h",qe.params="p",qe.reachGoal="g",qe.userParams=
"up",qe.trackHash="th",qe.accurateTrackBounce="atb",qe.notBounce="nb",qe.addFileExtension="fe",qe.extLink="el",qe.file="fc",qe.trackLinks="tl",qe.destruct="d",qe.setUserID="ui",qe.getClientID="ci",qe.clickmap="cm",qe.enableAll="ea",qe),se={mc:function(a){a=tc(a).m("mt",{});a=Qb(a);return a.length?E(function(b,c,d){var e=p(c);c=e.next().value;e=e.next().value;return""+b+(d?"-":"")+c+"-"+e},"",a):null},mtb:function(){return Math.min(je,1E5)}};
function te(a,b){if(!b)return null;try{return a.JSON.parse(b)}catch(c){return null}}function ue(a,b){try{return a.JSON.stringify(b,null,void 0)}catch(c){return null}}function ve(a){try{return a.localStorage}catch(b){}return null}function we(a,b){var c=ve(a);try{c.removeItem(b)}catch(d){}}function xe(a,b){var c=ve(a);try{return te(a,c.getItem(b))}catch(d){}return null}function ye(a,b,c){var d=ve(a);a=ue(a,c);if(!Pa(a))try{d.setItem(b,a)}catch(e){}}
var ze=w(function(a){ye(a,"_ymBRC","1");var b="1"!==xe(a,"_ymBRC");b||we(a,"_ymBRC");return b});function Ae(a,b,c){var d=""+(void 0===c?"_ym":c)+(void 0===b?"":b);d&&(d+="_");return{zc:ze(a),m:function(e,f){var g=xe(a,""+d+e);return Pa(g)&&!z(f)?f:g},A:function(e,f){ye(a,""+d+e,f);return this},Aa:function(e){we(a,""+d+e);return this}}}var Be=w(Ae),Ce=w(Ae,function(a,b,c){return""+b+c});function De(a){if(Qa(a))return!1;a=a.nodeType;return 3===a||8===a}function Ee(a){return a?a.innerText||"":""}
var Fe=w(function(a){a=G(a,"document")||{};return(""+(a.characterSet||a.charset||"")).toLowerCase()}),Ge=w(F(I("document"),C("createElement",gb)));function He(a){var b=a&&a.parentNode;b&&b.removeChild(a)}function Ie(a,b){try{return(new RegExp("(?:^|\\s)"+a+"(?:\\s|$)")).test(b.className)}catch(c){return!1}}
var Je=w(function(a){var b=G(a,"Element.prototype");return b?(a=Hd(function(c){var d=b[c];return!!d&&ua(c,d)},["matches","webkitMatchesSelector","mozMatchesSelector","msMatchesSelector","oMatchesSelector"]))?b[a]:null:null});function Ke(a){a=G(a,"document");try{return a.getElementsByTagName("body")[0]}catch(b){return null}}function Le(a){var b=G(a,"document")||{},c=b.documentElement;return"CSS1Compat"===b.compatMode?c:Ke(a)||c}
function Me(a){var b=G(a,"visualViewport.width"),c=G(a,"visualViewport.height");a=G(a,"visualViewport.scale");return Qa(b)||Qa(c)?null:[Math.floor(b),Math.floor(c),a]}function Ne(a){var b=Me(a);if(b){var c=p(b);b=c.next().value;var d=c.next().value;c=c.next().value;return[a.Math.round(b*c),a.Math.round(d*c)]}b=Le(a);return[G(b,"clientWidth")||a.innerWidth,G(b,"clientHeight")||a.innerHeight]}
function Oe(a){try{return a.getBoundingClientRect&&a.getBoundingClientRect()}catch(b){return a=b,"object"===typeof a&&null!==a&&16389===(a.Gc&&a.Gc&65535)?{top:0,bottom:0,left:0,width:0,height:0,right:0}:null}}var Pe=/\/$/;function Qe(a){var b=P(a),c=b.m("hitId");c||(c=dd(a),b.A("hitId",c));return c}function Re(a,b){var c=Be(a),d=Ad(a),e=b.Za||"uid";return[c.m(e),d.m(e)]}var Se=ed("r",function(a,b){var c=p(Re(a,b)),d=c.next().value;return!c.next().value&&d});
function Te(a,b){var c=b.Za,d=c||"uid";c=c?a.location.hostname:void 0;var e=Ad(a),f=Be(a),g=U(a)(Oc),h=p(Re(a,b)),k=h.next().value;h=h.next().value;var l=e.m("d");Se(a,b);var m=!1;!h&&k&&(h=k,m=!0);if(!h)h=S("",[g,dd(a,1E6,999999999)]),m=!0;else if(!l||15768E3<g-Mb(l))m=!0;m&&!b.Fa&&(e.A(d,h,525600,c),e.A("d",""+g,525600,c));f.A(d,h);return h}function Ue(a,b,c){return gb("setTimeout",a)(b,c)}function Ve(a,b){return gb("clearTimeout",a)(b)}
function We(a,b,c,d){return Ue(a,W(a,"d.err."+(d||"def"),b),c)}function Xe(a,b){return function(c){return c(a,b)}}function Ye(a){var b=[],c=!1;return ra(function(d,e){function f(g){b.push(g)===a.length&&d(b)}K(function(g){g(Xe(f,function(h){if(!c)try{e(h),c=!0}catch(k){f(k)}}))},a)})}function Ze(a){return ra(function(b,c){a.then(c,b)})}function $e(a){return ra(function(b,c){c(a)})}
function af(a){function b(e){G(c,d)?e():We(a,C(e,b),100)}var c=void 0===c?a:c;var d=(c.nodeType?"contentWindow.":"")+"document.body";return ra(function(e,f){b(f)})}function bf(a){var b=[],c={nd:b};c.C=F(Wa("push",b),C(c,v));c.Ha=F(na(za(a))(b),na(Wa("splice",b))(1),C(c,v));c.N=F(v,na(Od),Gb(b));return c}
function cf(a){var b={};return{C:function(c,d){K(function(e){G(b,e)||(b[e]=bf(a));b[e].C(d)},c);return this},Ha:function(c,d){K(function(e){G(b,e)&&b[e].Ha(d)},c);return this},N:function(c,d){return G(b,c)?W(a,"e."+c,b[c].N,[])(d):[]}}}var df=w(function(){return{Y:{},pending:{},children:{}}}),ef=I("postMessage");
function ff(a,b){return function(c,d){var e={Pa:U(a)(T),key:a.Math.random(),dir:0};c.length&&(e.Pa=Mb(c[0]),e.key=parseFloat(c[1]),e.dir=Mb(c[2]));M(d,b);var f={};f=(f.data=d,f.__yminfo=S(":",["__yminfo",e.Pa,e.key,e.dir]),f);return{meta:e,Rb:ue(a,f)||""}}}var gf=X("s.f",function(a,b,c,d,e){b=b(d);var f=df(a),g=S(":",[b.meta.Pa,b.meta.key]);if(ef(c)){f.pending[g]=e;try{c.postMessage(b.Rb,"*")}catch(h){delete f.pending[g];return}We(a,function(){delete f.pending[g]},5E3,"if.s")}});
function hf(a){if(ua("MutationObserver",a.MutationObserver)){var b=df(a).children,c=new a.MutationObserver(function(){K(function(d){G(b[d],"window.window")||delete b[d]},L(b))});af(a)(Xe(t,function(){c.observe(a.document.body,{subtree:!0,childList:!0})}))}}
function jf(a,b){var c=df(a);b.C(["initToParent"],function(d){var e=p(d);d=e.next().value;e=e.next().value;window.window&&(c.children[e.counterId]={info:e,window:d.source})}).C(["initToChild"],function(d){var e=p(d);d=e.next().value;e=e.next().value;d.source===a.parent&&b.N("parentConnect",[d,e])}).C(["parentConnect"],function(d){var e=p(d);d=e.next().value;e=e.next().value;e.counterId&&(c.Y[e.counterId]={info:e,window:d.source})})}
var kf=X("s.fh",function(a,b,c,d,e,f){var g=null,h=null,k=df(a),l=null;try{g=te(a,f.data),h=g.__yminfo,l=g.data}catch(m){return}if(!Qa(h)&&h.substring&&"__yminfo"===h.substring(0,8)&&!Qa(l)&&(a=h.split(":"),4===a.length))if(g=b.id,h=p(a),h.next(),b=h.next().value,a=h.next().value,h=h.next().value,!tb(l)&&l.type&&"0"===h&&l.counterId){if(!l.toCounter||l.toCounter==g){k=null;try{k=f.source}catch(m){}!Pa(k)&&ef(k)&&(f=d.N(l.type,[f,l]),e=K(F(v,Rb(e)),f.concat([void 0])),l=c([b,a,l.counterId],e),k.postMessage(l.Rb,
"*"))}}else h===""+g&&tb(l)&&nb(function(m){return!(!m.hid||!m.counterId)},l).length===l.length&&(c=k.pending[S(":",[b,a])])&&c.apply(null,[f].concat(l))}),lf=w(function(a,b){var c=gb("getElementsByTagName",G(a,"document")),d=df(a),e=ef(a),f=cf(a),g=Hc(a);if(!c||!e)return null;c=c.call(a.document,"iframe");e={};e=(e.counterId=b.id,e.hid=""+Qe(a),e);lc(a)&&(e.duid=Te(a,b));jf(a,f);hf(a);var h=ff(a,e),k=B([a,C([],h)],gf);K(function(l){var m=null;try{m=l.contentWindow}catch(n){}m&&k(m,{type:"initToChild"},
function(n,u){f.N("initToParent",[n,u])})},c);fc(a)&&k(a.parent,{type:"initToParent"},function(l,m){f.N("parentConnect",[l,m])});g.C(a,["message"],B([a,b,h,f,e],kf));return{ba:f,Y:d.Y,children:d.children,Mb:k}},F(Ca,O)),mf=w(function(a,b){if(!lc(a)||!fc(a))return Te(a,b);var c=lf(a,b);return c&&c.Y[b.id]?c.Y[b.id].info.duid||Te(a,b):Te(a,b)},function(a,b){return""+b.Za+b.Fa}),nf=w(F(U,ra(function(a){return-(new a.l.Date).getTimezoneOffset()}))),of=F(U,ra(function(a){a=new a.l.Date;return S("",K(Lc,
[a.getFullYear(),a.getMonth()+1,a.getDate(),a.getHours(),a.getMinutes(),a.getSeconds()]))})),pf=F(U,ra(Oc)),qf=w(F(U,ra(function(a){return p(a.T).next().value}))),rf=w(function(a){a=P(a);var b=a.m("counterNum",0)+1;a.A("counterNum",b);return b},F(Ca,O)),Y={},sf=(Y.vf=C(la.version,v),Y.nt=bc,Y.fu=function(a,b,c){var d=c.B;if(!d)return null;b=(G(a,"document.referrer")||"").replace(Pe,"");c=(d["page-ref"]||"").replace(Pe,"");d=d["page-url"];a=V(a).href!==d;b=b!==c;c=0;a&&b?c=3:b?c=1:a&&(c=2);return c},
Y.en=Fe,Y.la=dc,Y.ut=function(a,b,c){var d=c.F;c=c.B;d=d&&d.Ga;c&&(ld(a)||b.$b||d)&&(c.ut=N.ic);return null},Y.v=C(N.ea,v),Y.cn=rf,Y.dp=function(a){var b=P(a),c=b.m("bt",{});if(z(b.m("bt"))){var d=G(a,"navigator.getBattery");try{c.p=d&&d.call(a.navigator)}catch(e){}b.A("bt",c);c.p&&c.p.then&&c.p.then(W(a,"bi:dp.p",function(e){c.$c=G(e,"charging")&&0===G(e,"chargingTime")}))}return jb(c.$c)},Y.ls=w(function(a,b){var c=Ce(a,b.id),d=U(a),e=c.m("lsid");return+e?e:(d=dd(a,0,d(T)),c.A("lsid",d),d)},Ca),
Y.hid=Qe,Y.phid=function(a,b){if(!fc(a))return null;var c=lf(a,b);if(!c)return null;var d=L(c.Y);return d.length?c.Y[d[0]].info.hid:null},Y.z=nf,Y.i=of,Y.et=pf,Y.c=F(I("navigator.cookieEnabled"),ib),Y.rn=F(v,dd),Y.rqn=function(a,b,c){c=c.B;if(!c||c.nohit)return null;b=O(b);a=Ce(a,b);b=(a.m("reqNum",0)||0)+1;a.A("reqNum",b);if(a.m("reqNum")===b)return b;a.Aa("reqNum");return null},Y.u=mf,Y.w=function(a){var b=p(Ne(a));a=b.next().value;b=b.next().value;return a+"x"+b},Y.s=function(a){var b=G(a,"screen");
if(b){a=G(b,"width");var c=G(b,"height");b=G(b,"colorDepth")||G(b,"pixelDepth");return S("x",[a,c,b])}return null},Y.sk=I("devicePixelRatio"),Y.ifr=F(fc,ib),Y.j=F(hc,ib),Y.sti=function(a){return fc(a)&&gc(a)?"1":null},Y),tf=w(function(){return Nd(L(sf),L(se))});function uf(a){return function(b,c){return{H:function(d,e){var f=d.D,g=d.B;f&&g&&K(function(h){var k=sf[h],l="bi",m=f;k||(k=se[h],l="tel",m=me(d));k&&(k=X(l+":"+h,k,null)(b,c,d),m.gb(h,k))},a||tf());e()}}}}
function vf(a){return{H:function(b,c){var d=b.D;if(d){var e=a.document.title;b.F&&b.F.title&&(e=b.F.title);var f=gb("getElementsByTagName",a.document);"string"!==typeof e&&f&&(e=f("title"),e=(e=G(e,"0.innerHtml"))?e:"");e=e.slice(0,N.ec);d.A("t",e)}c()}}}var wf=w(Cd,O);function xf(a,b,c){if(lc(a)&&fc(a)){var d=wf(b);if(!d.Ac){d.Ac=!0;b=lf(a,b);if(!b){c();return}d.P=[];var e=function(){d.P&&(K(Od,d.P),d.P=null)};We(a,e,3E3);b.ba.C(["initToChild"],e)}d.P?d.P.push(c):c()}else c()}
var yf=w(function(){return{tb:null,P:[]}},O);function zf(a){return(a=a.D)&&a.m("pv")&&!a.m("ar")}function Af(a,b,c){var d=a.D;d?zf(a)?(b.tb=d,c()):b.P?b.P.push(c):c():c()}function Bf(a,b){return{H:function(c,d){var e=yf(b);e=B([c,e,d],Af);xf(a,b,e)},da:function(c,d){var e=c.D,f=yf(b);if(e){var g=f.P;f.tb===e&&g&&(K(Od,g),f.P=null)}d()}}}var Cf=/^[a-z][\w.+-]+:/i;
function Df(a,b){var c=V(a),d=c.href,e=c.host,f=-1;if(!Ia(b)||z(b))return d;c=b.replace(md,"");if(-1!==c.search(Cf))return c;var g=c.charAt(0);if("?"===g&&(f=d.search(/\?/),-1===f)||"#"===g&&(f=d.search(/#/),-1===f))return d+c;if(-1!==f)return d.substr(0,f)+c;if("/"===g){if(f=La(d,e),-1!==f)return d.substr(0,f+e.length)+c}else return d=d.split("/"),d[d.length-1]=c,S("/",d);return""}
function Ef(a){return{H:function(b,c){var d=b.B;if(!b.D||!d)return c();var e=d["page-ref"],f=d["page-url"];e&&f!==e?d["page-ref"]=Df(a,e):delete d["page-ref"];d["page-url"]=Df(a,f).slice(0,N.fc);return c()}}}var Ff=[[be,1],[Bf,2],[uf(),3],[vf,4]],Gf=[],Hf=C(Ff,Vd),If={},Jf=(If.h=Ff,If),Z=C(Jf,function(a,b,c,d){a[b]||(a[b]=[]);c&&!Qa(d)&&Vd(a[b],c,d)});Hf(Ef,-100);function Kf(a,b,c){b=tb(b)?b:Jf[b]||Ff;var d=K(wb,b);K(function(e){return d.unshift(e)},Gf);return K(F(ab([a,c]),Od),d)}
function Lf(a,b){var c=Ge(a);if(c){var d=a.document,e=c("script");e.src=b.src;e.type=b.type||"text/javascript";e.charset=b.charset||"utf-8";e.async=b.async||!0;try{var f=d.getElementsByTagName("head")[0];if(!f){var g=d.getElementsByTagName("html")[0];f=c("head");g&&g.appendChild(f)}f.insertBefore(e,f.firstChild);return e}catch(h){}}}var Mf=w(function(a){if(a=Ge(a))return a("a")});
function Nf(a,b){var c=Mf(a);return c?(c.href=b,{protocol:c.protocol,host:c.host,port:c.port,hostname:c.hostname,hash:c.hash,search:c.search,query:c.search.replace(/^\?/,""),pathname:c.pathname||"/",path:(c.pathname||"/")+c.search,href:c.href}):{}}function Of(a){return(a.split(":")[1]||"").replace(/^\/*/,"").replace(/^www\./,"").split("/")[0]}function Pf(a,b){if(!b||!b.length)return a;var c=p(a.split("#")),d=c.next().value;c=ca(c);c=(c=S("#",c))?"#"+c:"";return Na(a,"?")?d+"&"+b+c:d+"?"+b+c}
var Qf=/[^a-z0-9.:-]/;function Rf(a,b,c,d,e,f,g,h){if(4===b.readyState)if(200===b.status||e||g(c),e)200===b.status?f(b.responseText):g(xc("http."+b.status+".st."+b.statusText+".rt."+(""+b.responseText).substring(0,50)));else{e=null;if(d)try{(e=te(a,b.responseText))||g(c)}catch(k){g(c)}f(e)}return h}
function Sf(a,b,c){var d=new a.XMLHttpRequest,e=c.K,f={},g=M(c.ac?(f.wmode="7",f):{},c.Ja);return new Q(function(h,k){d.open(c.lb||"GET",Pf(b,cd(g)),!0);d.withCredentials=!1!==c.bd;c.Ub&&(d.timeout=c.Ub);F(Qb,Fb(function(m){var n=p(m);m=n.next().value;n=n.next().value;d.setRequestHeader(m,n)}))(c.ma);var l=B([a,d,ce(c.aa),c.ac,c.Kc,h,k],Rf);d.onreadystatechange=l;try{d.send(e)}catch(m){}})}
function Tf(a,b,c,d){return new Q(function(e,f){var g=Le(a),h=b("img"),k=F(C(h,He),C(ce(d.aa),f)),l=Ue(a,k,d.Ub||3E3);h.onerror=k;h.onload=F(C(h,He),C(null,e),B([a,l],Ve));l=M({},d.Ja);delete l.wmode;k=c;(l=cd(l))&&(k=Pf(k,l));d.K&&(k=Pf(k,d.K));h.src=k;Wb(a)&&(M(h.style,{position:"absolute",visibility:"hidden",width:"0px",height:"0px"}),g.appendChild(h))})}
var Uf={},Vf=(Uf.x={id:2,check:function(a){var b;if(b=G(a,"XMLHttpRequest"))if(b="withCredentials"in new a.XMLHttpRequest){a:{if(Qf.test(a.location.host)&&a.opera&&x(a.opera.version)&&(b=a.opera.version(),"string"===typeof b&&"12"===b.split(".")[0])){b=!0;break a}b=!1}b=!b}return b?C(a,Sf):!1}},Uf.i={id:4,check:function(a){var b=Ge(a);return b?B([a,b],Tf):!1}},Uf),Xf={};function Yf(a){if(a)return E(function(b,c){var d=Vf[c];d&&b.push(d);return b},[],a)}
function Zf(a){return Xf["*"]?Yf(Xf["*"]):a?Yf(Xf[a]):void 0}
var $f=["b","f","x","j","i"],ag=["x"],bg=["i"],cg={},dg=(cg.h=ag,cg),eg=w(function(a,b,c){(c=Zf(b)||Yf(c))||(c=Yf(b?dg[b]:$f));b=E(function(d,e){var f=e.check,g=e.id;(f=f(a))&&d.push([g,f]);return d},[],c||[]);b.length||de();return b},Ca),fg=Va(Q.reject,Q,ce()),gg={},hg=(gg.h=$d,gg),ig=X("g.sen",function(a,b,c){var d=eg(a,b);c=c?Kf(a,b,c):[];var e=hg[b],f=e?e(a,d,c):$d(a,d,c);return function(){var g=p(Ga(arguments)),h=g.next().value;g=ca(g);h=M(h,{I:M(void 0===h.I?{}:h.I,{aa:[b]})});return f.apply(null,
[h].concat(g))}},fg);function jg(a,b){return function(c){var d=c[a];d?(d.Ib=!0,d.Hb(b)):c[a]={promise:Q.resolve(b),Ib:!0,Hb:t}}}var kg=q(function(a,b){if(!b[a]){var c,d=new Q(function(e){c=e});b[a]={Hb:c,promise:d,Ib:!1}}return b[a].promise}),lg=w(F(Cd,ra));function mg(a,b,c){b=O(b);var d=Mc(a);c=M({tc:d(T)},c);d={};var e={};Fd(a,(e.counterKey=b,e.name="counterSettings",e.data=(d.settings=c,d),e));return lg()(jg(b,c))}function ng(a,b){var c=O(a);return lg()(kg(c)).then(b)}
function og(a,b){function c(d,e,f){var g={},h={};Fd(a,(h.name="log",h.counterKey=b,h.data=(g.args=tb(e)?e:[e],g.type=d,g.variables=f,g),h))}return{log:C("log",c),error:C("error",c),warn:C("warn",c)}}var pg=w(X("dc.init",function(a,b){return b&&fd(Kb(b.split(":")[0]))?{log:t,warn:t,error:t}:og(a,b)}),Ca);function qg(a,b,c,d){pg(a,b).log(c,d)}function rg(a,b,c,d,e){return B([a,O(b),e?[c+".p",e]:c,d],qg)}
function sg(a,b){if(a.postMessage&&!a.attachEvent){var c=Hc(a),d="__ym__promise_"+dd(a)+"_"+dd(a),e=t;e=c.C(a,["message"],W(a,"as",function(f){try{var g=f.data}catch(h){return}g===d&&(e(),f.stopPropagation&&f.stopPropagation(),b())}));a.postMessage(d,"*")}else We(a,b,0,"as")}
var tg=X("h.p",function(a,b){var c=ig(a,"h",b),d=b.Sa||""+V(a).href,e=b.vc||a.document.referrer,f={},g={};f={D:Jd((f.pv=1,f)),B:(g["page-url"]=d,g["page-ref"]=e,g),F:{}};f.F.G=b.G;b.Oa&&f.B&&(f.B.nohit="1");return c(f,b).then(function(h){if(h){if(!b.Oa){var k={};rg(a,b,"h",(k.id=b.id,k.url=d,k.ref=e,k),b.G)()}sg(a,B([a,b,h],mg))}})["catch"](W(a,"h.g.s"))});
function ug(a,b,c){try{if(x(b)){var d=p(Ga(arguments));d.next();d.next();d.next();var e=ca(d);b.apply(Qa(c)?null:c,e)}}catch(f){Ue(a,C(f,zc),0)}}var vg=["yandex_metrika_callback"+la.callbackPostfix,"yandex_metrika_callbacks"+la.callbackPostfix],wg=X("cb.i",function(a){var b=p(vg),c=b.next().value,d=b.next().value;if(x(a[c]))a[c]();"object"===typeof a[d]&&K(function(e,f){a[d][f]=null;ug(a,e)},a[d]);K(function(e){try{delete a[e]}catch(f){a[e]=void 0}},vg)});
function xg(a,b){var c=P(a).m("counters",{}),d=O(b);return c[d]}function yg(a,b,c,d){var e=re[c];return e?function(){var f=Ga(arguments);f=d.apply(null,da(f));var g=P(a);g.O("mt",{});g=g.m("mt");var h=g[e];g[e]=h?h+1:1;return f}:d}var zg=[],Ag=[],Bg=[],Cg=[],Dg=[],Eg=[],Fg=F(Ma,pa(0)),Gg=na(Fg);function Hg(a){a=P(a);var b=a.m("dsjf")||ra({});a.O("dsjf",b);return b}function Ig(a,b,c){Hg(a)(function(d){d[b]=M(d[b]||{},c)})}function Jg(a,b){Hg(a)(function(c){delete c[b]})}
function Kg(a,b){return function(c){Ig(a,b,c)}}var Lg=q(function(a,b){var c={};Hg(a)(function(d){c=d[b]||{}});return c}),Mg=X("c.c.cc",function(a){var b=P(a),c=F(Lg(a),function(d){var e={};e=(e.clickmap=!!d.clickmap,e);return M({},d,e)});return W(a,"g.c.cc",F(Va(b.m,b,"counters",{}),L,Fb(c)))}),Ng=X("gt.c.rs",function(a,b){var c=O(b),d=b.id,e=b.L,f=b.gd,g=b.sd,h=B([a,c],Jg),k={};Ig(a,c,(k.id=d,k.type=+e,k.clickmap=f,k.trackHash=!!g,k));return h}),Og={};
function Pg(a,b){var c=O(a),d=G(b,"__ym.turbo_page"),e=G(b,"__ym.turbo_page_id");Og[c]||(Og[c]={});if(d||e)Og[c].Vc=d,Og[c].Wc=e}function Qg(a){a=O(a);return Og[a]&&Og[a].Vc}var Rg=w(Dd);
function Sg(a,b){return{H:function(c,d){var e=(c.F||{}).G,f=void 0===c.I?{}:c.I;if(e&&(Pg(b,e),!f.K&&c.D&&c.B)){var g=ue(a,e),h=Rg(a),k=c.D.m("pv");if(g&&!c.B.nohit){var l={},m={};Fd(a,(m.counterKey=O(b),m.name="params",m.data=(l.val=e,l),m));k?encodeURIComponent(g).length>N.dc?h.push([c.D,e]):c.B["site-info"]=g:(f.K=g,c.I=f,c.Ia||(c.Ia={}),c.Ia.Fc=!0)}}d()},da:function(c,d){var e=Rg(a),f=xg(a,b),g=f&&f.params;g&&(f=nb(F(wb,pa(c.D)),e),K(function(h){var k=p(h);k.next();k=k.next().value;g(k);h=vb(a)(h,
e);e.splice(h,1)},f));d()}}}function Tg(a,b,c,d,e){var f=B([a,d,e],ug);return c.then(f,function(g){f();ge(a,b,g)})}var Ug=w(Cd,O);function Vg(a){var b=t,c=null,d=a.length;if(0!==a.length&&a[0]){var e=a.slice(-1)[0];x(e)&&(b=e,d=a.length+-1);var f=a.slice(-2)[0];x(f)&&(b=f,c=e,d=a.length+-2);d=a.slice(0,d);return{rc:c,za:b,G:1===d.length?a[0]:fb(d)}}}
var Wg=X("pa.int",function(a,b){var c={};return c.params=function(){var d=Ga(arguments),e=Vg(d);if(!e)return null;d=e.rc;var f=e.G;e=e.za;if(!Ra(f)&&!tb(f))return null;var g=ig(a,"1",b),h=Ug(b).url,k=!gd(b),l={};l=(l.id=b.id,l);var m=f;m.__ym&&(m=M({},f),m.__ym=E(function(u,r){var y=G(f,"__ym."+r);y&&(u[r]=y);return u},{},ne),L(m.__ym).length||delete m.__ym,k=!!L(m).length);m=JSON.stringify(m);l=rg(a,b,"pa",l,m);m={};var n={};g=g({F:{G:f},D:Jd((m.pa=1,m.ar=1,m)),B:(n["page-url"]=h||V(a).href,n)},
b).then(k?l:t);return Tg(a,"p.s",g,e,d)},c});function Xg(a,b,c,d,e){return(new Q(function(f,g){var h=L(c),k=F(d.resolve||v,qa(f)),l=F(d.reject||v,qa(g));d.resolve=k;d.reject=l;K(function(m){d.ib.push(+m);var n=c[m],u=We(a,C(ce(),l),5100,"is.m"),r={};b(n.window,M(e,(r.toCounter=Mb(m),r)),function(y,A){Ve(a,u);d.Pb.push(m);d.resolve&&d.resolve(A)})},h)}))["catch"](W(a,"if.b"))}
function Yg(a,b,c){b=nb(function(d){return!J(c.info.counterId,d.ib)},b);K(function(d){if(c.info.counterId){var e={};a((e[c.info.counterId]=c,e),d,d.data)}},b)}
function Zg(a,b){var c=lf(a,b),d=[],e=[];if(!c)return null;var f=B([a,c.Mb],Xg),g=C(f,Yg);c.ba.C(["initToParent"],function(h){h=p(h);h.next();h=h.next().value;g(d,c.children[h.counterId])}).C(["parentConnect"],function(h){h=p(h);h.next();h=h.next().value;g(e,c.Y[h.counterId])});return{ba:c.ba,rd:function(h,k){return new Q(function(l,m){c.Mb(h,k,function(n,u){l([n,u])});We(a,C(ce(),m),5100,"is.o")})},Lb:function(h){var k={Pb:[],ib:[],data:h};d.push(k);return f(c.children,k,h)},Nb:function(h){var k=
{Pb:[],ib:[],data:h};e.push(k);return f(c.Y,k,h)}}}var $g=w(Zg,F(Ca,O));function ah(a,b){if(!J(b,K(I("ymetrikaEvent.type"),a))){var c={},d={};a.push((d.ymetrikaEvent=(c.type=b,c),d))}}function bh(a){a=P(a);var b=a.m("dataLayer",[]);a.A("dataLayer",b);return b}
function ch(a,b,c){c=void 0===c?t:c;var d=void 0===d?!1:d;var e=bf(a);if(b&&x(b.push)){var f=b.push;b.push=function(){var g=Ga(arguments),h=p(g).next().value;d&&e.N(h);g=f.apply(b,g);d||e.N(h);return g};a={cb:e,unsubscribe:function(){b.push=f}};c(a);K(e.N,b);return a}}function dh(a,b){var c=G(b,"ymetrikaEvent");c&&a.N(G(c,"type"),c)}function eh(a,b,c){c=void 0===c?v:c;var d=cf(a);c(d);var e=C(d,dh);ch(a,b,function(f){f.cb.C(e)});return d}
function fh(a,b,c,d){var e=xg(a,c);if(e){a=d.data;c=""+c.id;var f=d.sended||[];d.sended||(d.sended=f);J(c,f)||!e.params||d.counter&&""+d.counter!==c||(e.params(a),f.push(c),d.parent&&(d={},b.Nb((d.type="params",d.data=a,d))))}}var gh=X("y.p",function(a,b){var c=Zg(a,b);if(c){var d=bh(a),e=B([a,c,b],fh);eh(a,d,function(f){f.C(["params"],e)});c.ba.C(["params"],F(I("1"),e))}});
function hh(a,b,c,d){var e=V(a),f=e.hostname;e=e.href;if(b=Ug(b).url)a=Nf(a,b),f=a.hostname,e=a.href;return[d+"://"+f+"/"+c,e||""]}
var ih={ld:Xa(/[/&=?#]/)},jh=X("go.in",function(a,b,c,d){c=void 0===c?"goal":c;var e={};return e.reachGoal=function(f,g,h,k){if(!f||ih[c]&&ih[c](f))return null;var l=g,m=h||t;x(g)&&(m=g,l=void 0,k=h);g={};var n=rg(a,b,"gr",(g.id=b.id,g.goal=f,g),l),u="goal"===c;g=ig(a,"g",b);var r=p(hh(a,b,f,c));h=r.next().value;r=r.next().value;var y={},A={};g=g({F:{G:l},D:Jd((y.ar=1,y)),B:(A["page-url"]=h,A["page-ref"]=r,A)},b).then(function(){u&&n();var H={},D={};Fd(a,(D.counterKey=O(b),D.name="event",D.data=(H.schema=
c,H.name=f,H.params=l,H),D));d&&d()});return Tg(a,"g.s",g,m,k)},e});function kh(a){var b=null;try{b=a.target||a.srcElement}catch(c){}if(b){3===b.nodeType&&(b=b.parentNode);for(a=b&&b.nodeName&&(""+b.nodeName).toLowerCase();G(b,"parentNode.nodeName")&&("a"!==a&&"area"!==a||!b.href&&!b.getAttribute("xlink:href"));)a=(b=b.parentNode)&&b.nodeName&&(""+b.nodeName).toLowerCase();return b.href?b:null}return null}
function lh(a,b){var c={};c=(c.string=!0,c.object=!0,c["boolean"]=b,c)[typeof b]||!1;var d={};a((d.trackLinks=c,d))}
function mh(a,b,c){var d=Jd();void 0!==c.Da&&d.A("ite",jb(c.Da));c.Ba&&d.A("dl",1);c.ia&&d.A("ln",1);var e=c.Zb||{},f={};d={D:d,F:{title:e.title||c.title,Ga:!!c.Ga,G:e.params},B:(f["page-url"]=c.url,f["page-ref"]=b.Sa||V(a).href,f)};f="Link";c.Ba?f=c.ia?"Ext link - File":"File":c.ia&&(f="Ext link");var g={},h={};Fd(a,(h.counterKey=O(b),h.name="event",h.data=(g.schema="Link click",g.name=(c.ia?"external":"internal")+" url: "+c.url,g),h));g={};b=c.sender(d,b).then(rg(a,b,"lcl",(g.prefix=f,g.id=b.id,
g.url=c.url,g),c.Zb));Tg(a,"cl.p.s",b,e.callback||t,e.ctx)}
function nh(a,b){if(a.Xc()){var c=kh(b);if(c&&!Ie("ym-disable-tracklink",c)){var d=a.l,e=a.qc,f=a.sa,g=a.sender,h=a.sc,k=f.Sa,l=c.href;var m=od(c.innerHTML&&c.innerHTML.replace(/<\/?[^>]+>/gi,""));m||(m=(m=c.querySelector("img"))?od(m.getAttribute("title")||m.getAttribute("alt")):"");m=l===m?"":m;var n=G(b,"isTrusted");if(Ie("ym-external-link",c))mh(d,f,{url:l,ia:!0,title:m,Da:n,sender:g});else{k=k?Nf(d,k).hostname:V(d).hostname;h=RegExp("\\.("+S("|",K(Oa,h))+")$","i");var u=c.protocol+"//"+c.hostname+
c.pathname;h=pe.test(u)||pe.test(l)||h.test(l)||h.test(u);c=c.hostname;kd(k)===kd(c)?h?mh(d,f,{url:l,Ba:!0,Da:n,title:m,sender:g}):m&&e.A("il",od(m).slice(0,100)):l&&oe.test(l)||mh(d,f,{url:l,Ga:!0,ia:!0,Ba:h,Da:n,title:m,sender:g})}}}}
var oh=q(function(a,b){Ia(b)?a.push(b):K(F(v,Wa("push",a)),b)}),ph=ed("retryReqs",function(a){var b=Be(a),c=b.m("retryReqs",{}),d=U(a)(T);K(function(e){var f=p(e);e=f.next().value;f=f.next().value;(!f||!f.time||f.time+864E5<d)&&delete c[e]},Qb(c));b.A("retryReqs",c);return c},!0);function qh(a){var b=ph(a);Be(a).A("retryReqs",b)}function rh(a,b){var c=ph(a);b.D&&!Pa(c)&&b.F&&(delete c[b.F.wa],qh(a))}
function sh(a,b){return{H:function(c,d){var e=c.D,f=c.V,g=c.B,h=void 0===c.I?{}:c.I;if(e&&g){var k=U(a);e.gb("rqnl",1);for(var l=ph(a),m=1;l[m];)m+=1;c.F||(c.F={});c.F.wa=m;var n={};l[m]=(n.protocol=N.fa,n.host=nc,n.resource=c.$.U,n.postParams=h.K,n.time=k(T),n.counterType=b.L,n.params=g,n.browserInfo=e.l(),n.counterId=b.id,n.ghid=Qe(a),n);f&&(l[m].telemetry=f.l());qh(a)}d()},da:function(c,d){rh(a,c);d()}}}
var th=[Gg("watch"),Gg("clmap")],uh=X("g.r",function(a){var b=U(a),c=ph(a),d=b(T),e=Qe(a);return E(function(f,g){var h=p(g),k=h.next().value;(h=h.next().value)&&Jb(ra(h.resource),th)&&!h.d&&h.ghid&&h.ghid!==e&&h.time&&500<d-h.time&&h.time+864E5>d&&2>=h.browserInfo.rqnl&&(h.d=1,k={protocol:h.protocol,host:h.host,U:h.resource,Hc:h.postParams,G:h.params,kc:h.browserInfo,jd:h.ghid,time:h.time,wa:Mb(k),pc:h.counterId,L:h.counterType},h.telemetry&&(k.V=h.telemetry),f.push(k));return f},[],Qb(c))});
function vh(a,b,c){function d(){r||(u=!0,y=!1,r=!0,f())}function e(){m=!0;k(!1);b()}function f(){Ve(a,l);if(m)k(!1);else{var R=Math.max(0,c-(y?A:A+n(T)-H));R?l=We(a,e,R,"u.t.d.c"):e()}}function g(){y=u=r=!0;A+=n(T)-H;H=n(T);f()}function h(){u||r||(A=0);H=n(T);u=r=!0;y=!1;f()}function k(R){R=R?D.C:D.xa;R(a,["blur"],g);R(a,["focus"],h);R(a.document,["click","mousemove","keydown","scroll"],d)}var l=0,m=!1;if(cc(a))return l=We(a,b,c,"u.t.d"),B([a,l],Ve);var n=U(a),u=!1,r=!1,y=!0,A=0,H=n(T),D=Hc(a);k(!0);
f();return function(){Ve(a,l);k(!1)}}
var wh=X("nb.p",function(a,b){function c(D){l()||(D="number"===typeof D?D:f,H=vh(a,d(!1),D),n())}function d(D){return function(R){var oa={};R=void 0===R?(oa.ctx={},oa.callback=t,oa):R;if(D||!y&&!k.zc){y=!0;n();H&&H();var ya=u(T);oa=(Mb(k.m("lastHit"))||0)<ya-18E5;var Vb=.1>Math.random();k.A("lastHit",ya);ya={};ya=Jd((ya.nb=1,ya.cl=A,ya.ar=1,ya));var Qd=Ug(b),Wf={};ya={B:(Wf["page-url"]=Qd.url||V(a).href,Wf),D:ya,F:{force:D}};me(ya,"nbe",e?1:0);Qd=pg(a,O(b)).warn;!R.callback&&R.ctx&&Qd("nbnc");(oa=
D||oa||Vb)||(oa=a.location.href,Vb=a.document.referrer,oa=!(oa&&Vb?Of(oa)===Of(Vb):!oa&&!Vb));if(oa)return oa=h(ya,b),Tg(a,"l.o.l",oa,R.callback,R.ctx)}return null}}var e=!1,f=15E3,g=Te(a,b);(e=5>Mb(g.substr(g.length-1)||"0"))&&(f=1E4);var h=ig(a,"n",b);g=O(b);var k=Ce(a,b.id),l=C(C(g,Lg(a)),F(Od,I("accurateTrackBounce"))),m={},n=C((m.accurateTrackBounce=!0,m),Kg(a,g)),u=U(a),r=u(T),y=!1,A=0,H;ng(b,function(D){A=D.tc-r});b.mb&&c(b.mb);g={};return g.notBounce=d(!0),g.u=H,g});
function xh(a){return!(!ua("querySelectorAll",G(a,"Element.prototype.querySelectorAll"))||!a.document.querySelectorAll)}function yh(a,b){if(!b||!b.querySelectorAll)return[];var c=b.querySelectorAll(a);return c?ub(c):[]}function zh(a,b){if(b.querySelector)return b.querySelector(a);var c=yh(a,b);return c&&c.length?c[0]:null}
function Ah(a,b,c){if(!(b&&b.Element&&b.Element.prototype&&b.document&&c))return null;if(b.Element.prototype.closest&&ua("closest",b.Element.prototype.closest)&&c.closest)return c.closest(a);var d=Je(b);if(d){for(b=c;b&&1===b.nodeType&&!d.call(b,a);)b=b.parentElement||b.parentNode;return b&&1===b.nodeType?b:null}if(xh(b)){for(a=ub((b.document||b.ownerDocument).querySelectorAll(a));c&&1===c.nodeType&&-1===za(b)(c,a);)c=c.parentElement||c.parentNode;return c&&1===c.nodeType?c:null}return null}
function Bh(a){a=""+a;for(var b=2166136261,c=a.length,d=0;d<c;d+=1)b^=a.charCodeAt(d),b+=(b<<1)+(b<<4)+(b<<7)+(b<<8)+(b<<24);return b>>>0}function Ch(a,b,c,d){return function(){if(xg(a,b)){var e=Ga(arguments);return d.apply(null,da(e))}}}S(",",K(function(a){return'input[type="'+a+'"]'},["button","submit","reset","file"]));
var Dh={},Eh=(Dh.transaction_id="id",Dh.item_brand="brand",Dh.index="position",Dh.item_variant="variant",Dh.value="revenue",Dh.item_category="category",Dh.item_list_name="list",Dh),Fh={},Gh=(Fh.item_id="id",Fh.item_name="name",Fh.promotion_name="coupon",Fh),Hh={},Ih=(Hh.promotion_name="name",Hh),Jh={},Kh=(Jh.promotion_name="name",Jh.promotion_id="id",Jh.item_id="product_id",Jh.item_name="product_name",Jh),Lh="currencyCode add delete remove purchase checkout detail impressions click promoView promoClick".split(" "),
Mh={},Nh=(Mh.view_item={event:"detail",W:Gh,Z:"products"},Mh.add_to_cart={event:"add",W:Gh,Z:"products"},Mh.remove_from_cart={event:"remove",W:Gh,Z:"products"},Mh.begin_checkout={event:"checkout",W:Gh,Z:"products"},Mh.purchase={event:"purchase",W:Gh,Z:"products"},Mh.view_item_list={event:"impressions",W:Gh},Mh.select_item={event:"click",Z:"products",W:Gh},Mh.view_promotion={event:"promoView",Z:"promotions",W:Kh},Mh.select_promotion={event:"promoClick",Z:"promotions",W:Kh},Mh);
function Oh(a,b){var c={};K(function(d){var e=a[d]||Eh[d]||d;-1!==La(d,"item_category")?(e=Eh.item_category,c[e]=c[e]?c[e]+("/"+b[d]):b[d]):c[e]=b[d]},L(b));return c}
function Ph(a,b){var c=Ia(a)?Nh[a]:a;if(c){var d=c.event,e=c.Z,f=void 0===c.wc?"items":c.wc,g=b.purchase||b,h=g[f];if(h){c=K(C(c.W,Oh),h);h={};var k={},l=(k[d]=e?(h[e]=c,h):c,k);c=L(g);e&&1<c.length&&(l[d].actionField=E(function(m,n){if(n===f)return m;if("currency"===n)return l.currencyCode=g.currency,m;m[Ih[n]||Eh[n]||n]=g[n];return m},{},c));return l}}}
var Qh=X("dl.w",function(a,b,c){function d(){var g=G(a,b);(e=tb(g)&&ch(a,g,c))||(f=We(a,d,1E3,"ec.dl"))}var e,f=0;d();return function(){return Ve(a,f)}});function Rh(a){var b=G(a,"ecommerce");if(Ra(b))return a=nb(qb(Lh),L(b)),a=E(function(c,d){c[d]=b[d];return c},{},a),0===L(a).length?void 0:a}
function Sh(a,b,c,d){if(c){var e=G(d,"ecommerce")||{};var f=G(d,"event")||"";e=Ra(e)&&Ia(f)?Ph(f,e):void 0;if(!e)a:{e=d;if(f=!tb(d))f=eb(d),f=a.isFinite(f)&&!a.isNaN(f)&&"[object Number]"===Object.prototype.toString.call(f);f&&(e=Ga(e));if(tb(e)){var g=p(e);e=g.next().value;f=g.next().value;g=g.next().value;if(Ia(f)&&Ra(g)&&"event"===e){e=Ph(f,g);break a}}e=void 0}if(d=e||Rh(d))e={},Fd(a,(e.counterKey=b,e.name="ecommerce",e.data=d,e)),a={},b={},c((b.__ym=(a.ecommerce=[d],a),b))}}
function Th(a,b,c){var d;a=[Qh(a,b,function(e){d=e;e.cb.C(c)}),function(){d&&d.unsubscribe()}];return B([Pd,a],K)}var Uh=X("p.e",function(a,b){var c=xg(a,b);if(c){var d=P(a);c=c.params;var e=W(a,"h.ee",B([a,O(b),c],Sh));return b.pb?(d.A("ecs",0),Th(a,b.pb,e)):ng(b,function(f){if((f=G(f,"settings.ecommerce"))&&Ia(f))return d.A("ecs",1),Th(a,f,e)})}});
function Vh(a,b,c,d,e){function f(k){return x(d)?d(k)?a.NodeFilter.FILTER_ACCEPT:a.NodeFilter.FILTER_REJECT:a.NodeFilter.FILTER_ACCEPT}e=void 0===e?-1:e;var g=void 0===g?!1:g;var h=f(b);if(x(c)&&(g||h===a.NodeFilter.FILTER_ACCEPT)&&(h&&c(b),!De(b)))for(b=a.document.createTreeWalker(b,e,d?{acceptNode:f}:null,!1);b.nextNode()&&!1!==c(b.currentNode););}var Wh=w(function(a){return S("[^\\d<>]*",a.split(""))}),Xh=w(function(a){return new RegExp(Wh(a),"g")});
function Yh(a){return new RegExp("(?:"+S("|",K(Wh,L(a)))+")")}function Zh(a){var b={7:"8",8:"7"};return 11===a.length&&b[a[0]]?""+b[a[0]]+a.slice(1):a}function $h(a,b){for(var c=[],d=a.split(""),e=b.split(""),f=0,g=0;g<a.length&&!(f>=e.length);g+=1){var h=d[g];"0"<=h&&"9">=h?(c.push(e[f]),f+=1):c.push(d[g])}return S("",c)+b.slice(f+1)}function ai(){return $a(function(a,b){var c=p(K(pd,b)),d=c.next().value;c=c.next().value;a[d]={ca:c,Na:b};var e=Zh(d);e!==d&&(a[e]={ca:Zh(c),Na:b});return a},{})}
function bi(a,b,c){if(!c)return[];var d=[],e=Yh(b),f=["script","style"];Vh(a,c,function(g){var h=G(g,"parentNode.nodeName")||"";g===c||J(h.toLowerCase(),f)||(h=ob(e.exec(g.textContent||"")||[]),K(function(k){var l=pd(k);z(b[l])||d.push({Gb:"text",va:g,Ka:l,ca:$h(k,b[l].ca),Tc:g.textContent||""})},h))},function(g){return e.test(g.textContent||"")?1:0},a.NodeFilter.SHOW_TEXT);return d}
function ci(a,b){var c=a.document.body;if(!c)return[];var d=Yh(b);return E(function(e,f){var g=G(f,"href");try{var h=decodeURI(g||"")}catch(n){h=""}var k=h;if("tel:"===k.slice(0,4)){var l=p(d.exec(k)||[]).next().value;h=l?pd(l):"";var m=b[h];z(m)||!h&&"*"!==m.Na[0]||(e.push({Gb:"href",va:f,Ka:h,ca:$h(l,b[h].ca),Tc:g}),g=pd(k.slice(4)),g=ai()([h?m.Na:[g,""]]),Nd(e,bi(a,g,f)))}return e},[],ub(c.querySelectorAll("a")))}
function di(a,b){af(a)(Xe(t,function(){var c=a.document.body,d={};d=(d.attributes=!0,d.childList=!0,d.subtree=!0,d);ua("MutationObserver",a.MutationObserver)&&(new MutationObserver(b.N)).observe(c,d)}))}function ei(a,b){function c(){e=0;f&&(f=!1,e=We(a,c,1E3),d.N(g))}var d=bf(a),e,f=!1,g;b.C(function(h){f=!0;g=h;e||c();return t});return d}
var fi=w(function(a){return Sb(a)||!xh(a)}),gi=w(function(a){a=V(a);a=bd(a.search.substring(1));return{id:Mb(a["_ym_status-check"]||""),lang:a._ym_lang||"ru"}}),hi=/[\*\.\?\(\)]/g,ii=w(function(a,b,c){try{var d=c.replace("\\s"," ").replace(hi,"");b={};pg(a,"").warn("nnw",(b.name=d,b))}catch(e){}},Ca),ji=X("r.nn",function(a){Bd(a)&&ch(a,sa,function(b){b.cb.C(function(c){var d=p(c);c=d.next().value;d=d.next().value;ii(a,d,c);sa.splice(100)})})});
function ki(a,b){return{H:function(c,d){zf(c)?d():ng(b,function(e){if(e=G(e,"settings.hittoken")){var f={};e=(f.hittoken=e,f);c.B=M(c.B||{},e)}d()})}}}
var li=w(Cd,O),mi=X("fpi",function(a){var b=Ic(a);if(b&&!a.document.hidden){var c=P(a).O;c("fpe",1);var d=Hc(a).C(a,["visibilitychange","webkitvisibilitychange"],function(){a.document.hidden&&(c("fht",b.now()),d())})}}),ni="FB_IAB FBAV OKApp GSA/ yandex yango uber EatsKit YKeyboard iOSAppUslugi YangoEats PassportSDK".split(" "),oi=w(function(a){var b=yb(a);a=b.Yb;if(!b.wb)return!1;b=Wa("indexOf",a);b=Jb(F(b,pa(-1),Da),ni);var c=/CFNetwork\/[0-9][0-9.]*.*Darwin\/[0-9][0-9.]*/.test(a),d=/YaBrowser\/[\d.]+/.test(a),
e=/Mobile/.test(a);return b||c||d&&e||!/Safari/.test(a)&&e}),pi=w(function(a){var b=zb(a);return b?Na(b,"YangoEats")||Zb(a):!1}),qi=[],ri=!1,si=!1;function ti(a){if(qi.length){var b=qi.shift();si?b():We(a,b,100)}else ri=!1}function ui(a,b,c){c=void 0===c?1:c;var d=void 0===d?Wc:d;si=Infinity===c;return ra(function(e,f){function g(){try{var k=b(d(a,c));h=h.concat(k)}catch(l){return e(l)}b(Tc);if(b(Qc))return f(h),ti(a);si?(b(d(a,1E4)),f(h),ti(a)):We(a,g,100)}var h=[];ri?qi.push(g):(ri=!0,g())})}
function vi(a){var b=Qb(sc);return Array.prototype.sort.call(b,a)}var wi=q(function(a,b){return P(b).m(a,null)});function xi(a,b){var c=G(b,"__ym.turbo_uid");c&&P(a).O("tpuid",c)}
var yi=w(function(a){return x(G(a,"yandex.getSiteUid"))?a.yandex.getSiteUid():null}),zi=[["domainLookupEnd","domainLookupStart"],["connectEnd","connectStart"],["responseStart","requestStart"],["responseEnd","responseStart"],["fetchStart","navigationStart"],["redirectEnd","redirectStart"],[function(a,b){return G(b,"redirectCount")||G(a,"navigation.redirectCount")}],["domInteractive","domLoading"],["domContentLoadedEventEnd","domContentLoadedEventStart"],["domComplete","navigationStart"],["loadEventStart",
"navigationStart"],["loadEventEnd","loadEventStart"],["domContentLoadedEventStart","navigationStart"]],Ai=[["domainLookupEnd","domainLookupStart"],["connectEnd","connectStart"],["responseStart","requestStart"],["responseEnd","responseStart"],["fetchStart"],["redirectEnd","redirectStart"],["redirectCount"],["domInteractive","responseEnd"],["domContentLoadedEventEnd","domContentLoadedEventStart"],["domComplete"],["loadEventStart"],["loadEventEnd","loadEventStart"],["domContentLoadedEventStart"]],Bi=
{},Ci=(Bi.responseEnd=1,Bi.domInteractive=1,Bi.domContentLoadedEventStart=1,Bi.domContentLoadedEventEnd=1,Bi.domComplete=1,Bi.loadEventStart=1,Bi.loadEventEnd=1,Bi.unloadEventStart=1,Bi.unloadEventEnd=1,Bi.secureConnectionStart=1,Bi),Di=w(Dd);
function Ei(a,b,c){return K(function(d){var e=p(d),f=e.next().value;e=e.next().value;if(x(f))return f(a,b)||null;if(1===d.length)return b[f]?Math.round(b[f]):null;var g;!(g=b[f]&&b[e])&&(g=0===b[f]&&0===b[e])&&(g=p(d),d=g.next().value,g=g.next().value,g=!(Ci[d]||Ci[g]));if(!g)return null;f=Math.round(b[f])-Math.round(b[e]);return 0>f||36E5<f?null:f},c)}
function Fi(a,b){var c=a.length?K(function(d,e){var f=b[e];return f===d?null:f},a):b;a.length=0;K(F(v,Wa("push",a)),b);return nb(pa(null),c).length===a.length?null:c}
var Gi=[[["'(-$&$&$'",30102,0],["'(-$&$&$'",29009,0]],[["oWdZ[nc[jh_YW$Yec",30103,1],["oWdZ[nc[jh_YW$Yec",29010,1]]],Hi=[[["oWdZ[nc[jh_YW$Yec",30103,1]],[["oWdZ[nc[jh_YW$Yec",29010,1]]],Ii={B:{t:'UV|L7,!"T[rwe&D_>ZIb\\aW#98Y.PC6k'}},Ji={Sb:60,error:15},Ki={Sb:5,error:1},Li={id:42822899,L:"0"},Mi={},Ni=(Mi.am="com.am",Mi.tr="com.tr",Mi.ge="com.ge",Mi.il="co.il",Mi["\u0440\u0444"]="ru",Mi["xn--p1ai"]="ru",Mi["\u0431\u0435\u043b"]="by",Mi["xn--90ais"]="by",Mi),Oi={"mc.edadeal.ru":/^([^/]+\.)?edadeal\.ru$/,
"mc.yandexsport.ru":/^([^/]+\.)?yandexsport\.ru$/,"mc.kinopoisk.ru":/^([^/]+\.)?kinopoisk\.ru$/},Pi={},Qi=(Pi.ka="ge",Pi.ro="md",Pi.tg="tj",Pi.tk="tm",Pi.et="ee",Pi.hy="com.am",Pi.he="co.li",Pi.ky="kg",Pi.be="by",Pi.tr="com.tr",Pi.kk="kz",Pi);function Ri(a,b){var c=vi(function(d,e){return d[1].X>e[1].X?1:-1});c=K(function(d){var e=p(d);d=e.next().value;var f=e.next().value.bb;e=db(b,d)&&!Qa(b[d]);d=b[d]!==(f||v)(void 0);return jb(e&&d)},c);return Nb(S("",c))}
var Si=/^https?:\/\//,Ti={1882689622:1,2318205080:1,3115871109:1,3604875100:1,339366994:1,849340123:1,3735661796:1,3082499531:1,2343947156:1,655012937:1,3724710748:1,3364370932:1,1996539654:1,2065498185:1,823651274:1,12282461:1,1555719328:1,1417229093:1,138396985:1,3015043526:1},Ui=w(function(){return E(function(a,b){a[Bh(b+"/tag_turbo.js")]=1;return a},{},["mc.yandex.ru/metrika","mc.yandex.com/metrika","cdn.jsdelivr.net/npm/yandex-metrica-watch"])}),Vi="ar:1:pv:1:v:"+N.ea+":vf:"+la.version,Wi=N.fa+
"//"+nc+"/watch/"+N.bc;function Xi(a,b){try{var c=p(b),d=p(c.next().value);d.next();var e=d.next().value}catch(f){return function(){return Q.resolve()}}return function(f){var g={};g=(g["browser-info"]=Vi,g["page-url"]=a.location&&""+a.location.href,g);return e&&(f=ue(a,f))?e(Wi,{Ja:g,aa:[],K:"site-info="+$c(f)})["catch"](t):Q.resolve()}}
var Yi={},Zi=X("exps.int",function(a,b){var c={};return c.experiments=function(d,e,f){if(Ia(d)&&!(0>=d.length)){var g=ig(a,"e",b),h=Ug(b).url,k={},l={};d=g({D:Jd((k.ex=1,k.ar=1,k)),B:(l["page-url"]=h||V(a).href,l.exp=d,l)},b);return Tg(a,"exps.s",d,e||t,f)}},c}),$i=X("p.tpg",function(a,b){xi(a,b.G)}),aj=[],bj=X("p.fh",function(a,b){b=void 0===b?!0:b;var c=Be(a),d=U(a),e=c.m("wasSynced"),f={id:3,L:"0"};if(b&&e&&e.time+864E5>d(T))return Q.resolve(e);e={};var g={};return ig(a,"f",f)({D:Jd((e.pv=1,e)),
B:(g["page-url"]=V(a).href,g["page-ref"]=a.document.referrer,g)},f).then(function(h){var k={};h=(k.time=d(T),k.params=G(h,"settings"),k.bkParams=G(h,"userData"),k);c.A("wasSynced",h);return h})["catch"](W(a,"f.h"))}),cj=F(I("settings.pcs"),pa("1"));
function dj(a,b,c){var d=b||{},e=ig(a,"u",c),f=Be(a);return{m:function(g,h){return z(d[g])?f.m(g,h):d[g]},A:function(g,h){var k=""+h;d[g]=k;f.A(g,k);var l={};return e({B:(l.key=g,l.value=k,l)},[N.fa+"//"+nc+"/user_storage_set"],{})["catch"](W(a,"u.d.s.s"))}}}
var ej=w(function(a){a=V(a).hostname.split(".");return a[a.length-1]}),fj=w(function(a){return-1!==V(a).hostname.search(/(?:^|\.)(?:ya|yandex|beru|kinopoisk|edadeal)\.(?:\w+|com?\.\w+)$/)}),gj=RegExp("^(.*\\.)?((yandex(-team)?)\\.(com?\\.)?[a-z]+|(auto|kinopoisk|beru|bringly)\\.ru|ya\\.(ru|cc)|yadi\\.sk|yastatic\\.net|.*\\.yandex|turbopages\\.org|turbo\\.site|diplodoc\\.(com|tech)|datalens\\.tech|white-label\\.yango-tech\\.com|al-sadhan\\.com|spar\\.sa)$"),hj=w(function(a){a=V(a).hostname;var b=!1;
a&&(b=-1!==a.search(gj));return b}),ij=RegExp("^(.*\\.)?((yandex(-team)?)\\.(com?\\.)?[a-z]+|(auto|kinopoisk|beru|bringly)\\.ru|ya\\.(ru|cc)|yadi\\.sk|.*\\.yandex|turbopages\\.org|turbo\\.site)$"),jj=w(function(a){a=V(a).hostname;var b=!1;a&&(b=-1!==a.search(ij));return b}),kj={},lj=(kj.s="p",kj["8"]="i",kj),mj=ed("csp",function(a,b){return ig(a,"s",b)({},["https://ymetrica1.com/watch/3/1"])});
function nj(a,b,c){var d=c.Ic,e=c.data,f=ig(a,d,c.sa);a=M({},Ii);e&&M(a.B,e);return Ye(K(function(g){return Ze(f(M({I:{bd:!1,Kc:!0}},Ii),K(function(h){var k=p(h),l=k.next().value;h=k.next().value;k=k.next().value;l=S("",K(function(m){return String.fromCharCode(m.charCodeAt(0)+10)},l.split("")));return"http"+(k?"s":"")+"://"+l+":"+h+"/"+lj[d]},g)).then(function(h){return M({},h,{host:g[h.Xb]})}))},b))}
function oj(a,b,c,d,e,f){var g=f.Cb,h=f.sa,k=f.na;return new Q(function(l,m){var n=c.m(g,0);n=parseInt(""+n,10);return b(Nc)-n<=e.Sb?(k(3),m()):jj(a)?l(void 0):cj(d)?(k(4),m()):l(mj(a,h)["catch"](F(qa(C(5,k)),zc)))})}function pj(a,b,c,d,e){var f=void 0===e.Tb?t:e.Tb,g=e.Cb,h=void 0===e.na?t:e.na,k=d(T);return nj(a,b,e)(Xe(function(l){h(6);K(function(m){m&&ge(a,g+".s",m)},l);l=d(Nc);c.A(g,l).then(C(7,h))},function(l){h(8);c.A(g,d(Nc)).then(C(9,h));f(l,d,k)}))}
function qj(a){var b=$b(a);a=F(Ub,qb(["iPhone","iPad"]))(a);return b?Gi:a?Hi:[]}function rj(a,b,c){var d=c.sa,e=void 0===c.na?t:c.na,f=U(a),g=dj(a,b.userData,d),h=qj(a),k=F(ld,B([Ki,Ji],hb))(a),l=G(b,"settings.sbp");c.na=e;if(l){var m={};c.data=M({},l,(m.c=d.id,m))}return h.length?oj(a,f,g,b,k,c).then(function(){return pj(a,h,g,f,c)},t):(e(2),Q.resolve())}function sj(a,b){this.l=a;this.type=b}sj.isEnabled=function(a){return!!a.JSON};sj.prototype.Ma=function(a){return $e(ue(this.l,a))};
function tj(a,b){return{H:function(c,d){var e=c.B;e.wmode="0";e["wv-hit"]=e["wv-hit"]||""+Qe(a);e["page-url"]=e["page-url"]||V(a).href;var f={};e={$:{U:"webvisor/"+b.id},I:M(c.I||{},{ma:(f["Content-Type"]="text/plain",f),lb:"POST"}),B:e};M(c,e);d()}}}var uj="resize scroll mousemove mousedown click windowfocus keydown orientationchange change focus touchmove touchstart".split(" "),vj="id pageTitle stamp chars authors updateDate publicationDate pageUrlCanonical topics rubric".split(" ");
function wj(a,b,c,d,e){var f=this;this.Ca=!1;this.meta={};this.scroll={x:0,y:0};this.involvedTime=this.Bb=0;this.$a=this.Eb="";this.J=[];this.fb=this.Uc=0;this.oa={h:0,w:0};this.buffer=[];this.cc=vj;this.flush=function(){f.fb=We(f.l,f.flush,2500);var g=f.Ua();if(f.buffer.length||g){var h=xb(f.buffer);g&&h.push(g);f.Eb=f.$a;f.Oc.Ma(h)(Xe(W(f.l,"p.b.st"),function(k){k&&f.Nc(k)}))}};this.Nc=d;this.Oc=c;this.ya=Va(this.ya,this);this.Ua=Va(this.Ua,this);this.flush=Va(this.flush,this);this.l=a;this.ga=
e;this.La=b;this.Xa="pai"+b.id;xj(this);this.qb=Hc(this.l);this.time=U(this.l);yj(this);this.Va=P(this.l);this.kb=null}aa=wj.prototype;aa.start=function(){this.fb=We(this.l,this.flush,2500);if(!this.Ca){this.qb.C(this.l,uj,this.ya);var a=this.Va.m(this.Xa,[]),b=!a.length;a.push(Va(this.Bc,this));this.Va.O(this.Xa,a);b&&this.Kb();this.kb=Hc(this.l).C(this.l,["click"],Va(this.Pc,this));this.ya({type:"page",target:this.l})}};
aa.stop=function(){this.kb&&this.kb();this.qb.xa(this.l,uj,this.ya);this.Ca=!0;this.flush();Ve(this.l,this.fb)};aa.Kb=function(){var a=this;W(this.l,"p.ic"+this.La.id,function(){if(!a.Ca){var b=a.Va.m(a.Xa),c=zj(a.La);K(function(d){var e=K(function(f){return M({},f)},c);x(d)&&d(e)},b);a.Uc=We(a.l,Va(a.Kb,a),1E3,"p")}})()};aa.Bc=function(a){this.Ca||(Aj(this,a),Bj(this),Cj(this))};aa.lc=function(a,b){return(a.eb||0)<=(b.eb||0)?b:a};
aa.Pc=function(a){if(this.J.length){a=kh(a);var b=V(this.l).hostname;a&&kd(a.hostname)===kd(b)&&(a=E(this.lc,this.J[0],this.J).id,b=Qe(this.l),Ce(this.l,this.ga.split(":")[0]).A("pai",a+"-"+b))}};
aa.ya=function(a){var b=this;W(this.l,"p.ec."+this.La.id,function(){try{var c=a.type;var d=a.target}catch(k){return}var e="page"===c;if("scroll"===c||e){var f=[b.l,b.l.document,b.l.document.documentElement,Ke(b.l)];J(d,f)&&xj(b)}("resize"===c||e)&&yj(b);c=b.time(T);var g=Math.min(c-b.Bb,5E3);b.involvedTime+=Math.round(g);b.Bb=c;if(b.meta&&b.scroll&&b.oa){var h=b.oa.h*b.oa.w;b.J=K(function(k){var l=M({},k),m=b.meta[l.id],n=Oe(k.ra);if(!m||Ah("html",b.l,l.element)!==b.l.document.documentElement||!n)return l;
k=b.l.Math;m=k.max((b.scroll.y+b.oa.h-m.y)/m.height,0);var u=n.height*n.width,r=b.oa,y=n.top,A=n.bottom,H=n.left,D=r.w;r=r.h;var R=b.l.Math;n=R.min(R.max(n.right,0),D)-R.min(R.max(H,0),D);n*=R.min(R.max(A,0),r)-R.min(R.max(y,0),r);l.eb=n/h;l.visibility=n/u;if(.9<=l.visibility||.1<=l.eb)l.involvedTime+=g;l.maxScrolled=k.round(1E4*m)/1E4;return l},b.J);c={};d={};Fd(b.l,(d.name="publishers",d.counterKey=b.ga,d.data=(c.involvedTime=b.involvedTime,c.contentItems=K(function(k){var l={};return M((l.contentElement=
k.ra,l),k)},b.J),c),d))}})()};function Aj(a,b){var c=K(function(d){return d.id},a.J);a.J=a.J.concat(nb(function(d){return!J(d.id,c)},b))}function yj(a){var b=p(Me(a.l)||Ne(a.l)),c=b.next().value;b=b.next().value;a.oa={w:c,h:b}}
function Bj(a){W(a.l,"p.um."+a.La.id,function(){var b=[];xj(a);a.meta=E(function(c,d){if(Ah("html",a.l,d.element)!==a.l.document.documentElement)return b.push(d),delete c[d.id],c;var e={};e=(e.id=d.id,e.involvedTime=Math.max(d.involvedTime,0),e.maxScrolled=d.maxScrolled||0,e.chars=d.update?d.update("chars")||0:0,e);if(d.ra){var f=Oe(d.ra);f&&(e.x=Math.max(Math.round(f.left)+a.scroll.x,0),e.y=Math.max(Math.round(f.top)+a.scroll.y,0),e.width=Math.round(f.width),e.height=Math.round(f.height))}c[d.id]=
e;return c},{},a.J);K(function(c){c=vb(a.l)(c,a.J);a.J.splice(c,1)},b)})()}aa.Ua=function(){var a=K(C(this.meta,G),L(this.meta));if(a.length&&(this.$a=ue(this.l,a),this.Eb!==this.$a)){var b={},c={};return c.type="publishersHeader",c.data=(b.articleMeta=a||[],b.involvedTime=this.involvedTime,b),c}return null};
function Cj(a){if(a.J.length){var b=K(function(c){var d=E(function(f,g){c[g]&&(f[g]=c[g]);return f},{},a.cc);c.Ob=!0;var e={};return e.type="articleInfo",e.stamp=d.stamp,e.data=d,e},nb(function(c){return!c.Ob},a.J));b.length&&(a.buffer=a.buffer.concat(b),qg(a.l,a.ga,["pdf",b]))}}function xj(a){a.scroll={x:a.l.pageXOffset||G(a.l,"document.documentElement.scrollLeft")||0,y:a.l.pageYOffset||G(a.l,"document.documentElement.scrollLeft")||0}}var Dj={},Ej=(Dj[1]=500,Dj[2]=500,Dj[3]=0,Dj);
function Fj(a,b,c){var d=b.getAttribute("itemtype");c=yh('[itemprop~="'+c+'"]',b);return d?nb(function(e){return e.parentNode&&Ah("[itemtype]",a,e.parentNode)===b},c):c}function Gj(a,b,c){return(a=Fj(a,b,c))&&a.length?a[0]:null}function Hj(a){if(!a)return"";a=tb(a)?a:[a];return a.length?a[0].getAttribute("content")||Ee(a[0]):""}function Ij(a){return a?a.attributes&&a.getAttribute("datetime")?a.getAttribute("datetime"):Hj(a):""}var Jj=["topics","rubric","authors"];
function Kj(a,b){var c=this;this.id="a";this.xb=!1;this.Qa={};this.Lc={"schema.org":"Article NewsArticle Movie BlogPosting Review Recipe Answer".split(" "),od:["article"]};var d={};this.Wb=(d.Answer=3,d.Review=2,d);this.rb=w(function(e,f,g){var h={};qg(c.l,c.ga,"pfi",(h.field=e,h.itemField=f,h.value=g,h))},function(e,f,g){return""+e+f+g});this.ad=function(e){K(function(f){e[f]&&(e[f]=E(function(g,h){var k=h.name,l=h.position;if(!k)return c.rb(f,"name",k),g;if("string"===typeof l){k=Kb(l);if(null===
k||c.l.isNaN(k))return c.rb(f,"position",l),g;h.position=k}g.push(h);return g},[],e[f]))},Jj);return e};this.oc=w(function(e,f){var g={};qg(c.l,c.ga,["pcs",f],(g.chars=f.chars,g.limit=Ej[f.type],g))});this.l=a;this.root=Le(a);this.ga=b}function Lj(a,b,c){var d;W(a.l,"P.s."+c,function(){d=a.Qa[c].call(a,b)})();return d}
function Mj(a,b){var c=M({},b);if(a.xb&&!c.id&&J(b.type,[3,2])){var d=S(", ",K(I("name"),c.authors||[]));c.pageTitle=d+": "+c.pageTitle}if(!c.pageTitle){a:{d=c.ra;for(var e=1;5>=e;e+=1){var f=Hj(zh("h"+e,d));if(f){d=f;break a}}d=void 0}c.pageTitle=d}c.pageUrlCanonical||(d=c.id,d=("string"!==typeof d?0:/^(https?:)\/\//.test(d))?c.id:(d=zh('[rel="canonical"]',a.root))?d.href:void 0,c.pageUrlCanonical=d);c.id||(c.id=c.pageTitle||c.pageUrlCanonical);return c}
Kj.prototype.Ta=function(a){var b=this,c={},d=a.element;if(!d)return null;c.type=a.type;K(function(f){c[f]=Lj(b,a,f)},L(this.Qa));var e=U(this.l);c.stamp=e(Pc);c.element=a.element;c.ra=d;c=this.ad(Mj(this,c));c.id=c.id?Bh(c.id):1;c.update=function(f){return a.element?Lj(b,a,f):void 0};return c};Kj.prototype.getType=function(){return 1};Kj.prototype.sb=function(){return[]};
function zj(a){var b=a.sb(),c=1;return E(function(d,e){var f=a.Ta({element:e,type:a.getType(e)})||[];tb(f)||(f=[f]);f=E(function(g,h){var k=g.values,l=g.vb;h&&h.chars>Ej[h.type]&&!J(h.id,l)?(k.push(h),l.push(h.id)):h&&h.chars<=Ej[h.type]&&a.oc(h.id,h);return{values:k,vb:l}},{values:[],vb:K(I("id"),d)},f).values;return d.concat(K(function(g){var h={};g=M((h.index=c,h.Ob=!1,h.involvedTime=0,h),g);c+=1;return g},f))},[],b)}
function Nj(){Kj.apply(this,arguments);this.id="s";this.xb=!0;this.Zc=Wa("exec",new RegExp("schema.org\\/("+S("|",L(this.Wb))+")$"));var a={};this.Qa=(a.id=function(b){b=b.element;var c=Gj(this.l,b,"identifier");return c?Hj(c):(c=Gj(this.l,b,"mainEntityOfPage"))&&c.getAttribute("itemid")?c.getAttribute("itemid"):null},a.chars=function(b){var c=0;b=b.element;for(var d=["articleBody","reviewBody","recipeInstructions","description","text"],e=0;e<d.length;e+=1){var f=Gj(this.l,b,d[e]);if(f){c=Hj(f).length;
break}}b=Ee(b);0===c&&b&&(c+=b.length);return c},a.topics=function(b){var c=this,d=Fj(this.l,b.element,"about");return K(function(e){var f={name:Hj(e)};if(d=Gj(c.l,e,"name"))f.name=Hj(d);return f},d)},a.rubric=function(b){var c=this;(b=zh('[itemtype$="schema.org/BreadcrumbList"]',b.element))||(b=zh('[itemtype$="schema.org/BreadcrumbList"]',this.root));return b?K(function(d){return{name:Hj(Gj(c.l,d,"name")),position:Hj(Gj(c.l,d,"position"))}},Fj(this.l,b,"itemListElement")):[]},a.updateDate=function(b){return(b=
Gj(this.l,b.element,"dateModified"))?Ij(b):""},a.publicationDate=function(b){return(b=Gj(this.l,b.element,"datePublished"))?Ij(b):""},a.pageUrlCanonical=function(b){b=Fj(this.l,b.element,"url");if(b.length){var c=b[0];return c.href?c.href:Hj(b)}return null},a.pageTitle=function(b){var c="",d=b.element,e=Gj(this.l,d,"headline");e&&(c+=Hj(e));(e=Gj(this.l,d,"alternativeHeadline"))&&(c+=" "+Hj(e));""===c&&((e=Gj(this.l,d,"name"))||(e=Gj(this.l,d,"itemReviewed")),e&&(c+=Hj(e)));3===b.type&&(b=Ah('[itemtype$="schema.org/Question"]',
this.l,d))&&(b=Gj(this.l,b,"text"))&&(c+=Hj(b));return c},a.authors=function(b){var c=this;b=Fj(this.l,b.element,"author");return K(function(d){var e={};e=(e.name="",e);if(/.+schema.org\/(Person|Organization)/.test(d.getAttribute("itemtype")||"")){var f=Gj(c.l,d,"name");f&&(e.name=Hj(f))}e.name||(e.name=d.getAttribute("content")||Ee(d)||d.getAttribute("href"));return e},b)},a)}Nj.prototype=ea(Kj.prototype);Nj.prototype.constructor=Nj;
if(ka)ka(Nj,Kj);else for(var Oj in Kj)if("prototype"!=Oj)if(Object.defineProperties){var Pj=Object.getOwnPropertyDescriptor(Kj,Oj);Pj&&Object.defineProperty(Nj,Oj,Pj)}else Nj[Oj]=Kj[Oj];Nj.prototype.getType=function(a){a=a.getAttribute("itemtype")||"";return(a=this.Zc(a))?this.Wb[a[1]]:1};Nj.prototype.Ta=function(a){return a.element&&Ee(a.element).length?Kj.prototype.Ta.call(this,a):null};
Nj.prototype.sb=function(){var a=S(",",K(function(b){return'[itemtype$="schema.org/'+b+'"]'},this.Lc["schema.org"]));return yh(a,this.root)};function Qj(a,b,c,d,e){d=eg(a,c,d);b=Kf(a,e||c,b);var f=Yd(a,d,b);return function(g){g=M({I:{aa:["mms."+c]}},g);return f(g)}}var Rj="et w v z i u vf".split(" "),Sj={};Nj&&(Sj.schema=Nj,Sj.microdata=Nj);
var Tj=X("p.p",function(a,b){function c(l){var m=M({},k);m.I.K=l;return e(m)["catch"](W(a,"s.ww.p"))}var d=sj.isEnabled(a)?new sj(a,"8"):void 0;if(!ua("querySelectorAll",a.document.querySelectorAll)||!d)return Q.resolve();var e=Qj(a,b,"p",["f","x"],[[uf(Rj),1],[tj,1]]),f=Jd(),g=Ce(a,b.id),h=g.m("pai");h&&(g.Aa("pai"),f.A("pai",h));g={};var k={B:(g["wv-type"]=d.type,g),D:f,I:{}};return ng(b,W(a,"ps.s",function(l){if(l=G(l,"settings.publisher.schema")){Qg(b)&&(l="microdata");var m=Sj[l];if(m&&d){var n=
O(b);m=new m(a,n);m=new wj(a,m,d,c,n);m.start();var u={};qg(a,n,"ps",(u.schema=l,u));return Va(m.stop,m)}}}))});function Uj(a,b,c,d,e){d=void 0===d?1:d;e=void 0===e?"itc":e;b=Yc(b,c);ui(a,b,d)(Xe(W(a,e),t))}function Vj(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)}
var Wj=w(function(a){var b=P(a),c=b.m("isEU");if(z(c)){var d=Mb(td(a,"is_gdpr")||"");if(J(d,[0,1]))b.A("isEU",d),c=!!d;else if(a=Be(a).m("wasSynced"),a=G(a,"params.eu"))b.A("isEU",a),c=!!a}return c},function(a){return P(a).m("isEU")}),Xj=X("i.ep",function(a){Wj(a)}),Yj=N.fa+"//"+nc+"/metrika",Zj=Yj+"/metrika_match.html",ak=w(function(a){return{hd:a,ha:null,ja:[]}});
function bk(a){var b=ak(Zj);J("sc",b.ja)||b.ja.push("sc");if(Pa(b.ha)){var c=Ge(a);if(!c)return null;c=c("iframe");M(c.style,{display:"none",width:"1px",height:"1px",visibility:"hidden"});c.src=Zj;a=Le(a);if(!a)return null;a.appendChild(c);b.ha=c}else(a=G(b.ha,"contentWindow"))&&a.postMessage("frameReinit","*");return b.ha}function ck(a){a=ak(a);J("sc",a.ja)&&(a.ja=nb(F(pa("sc"),Da),a.ja),a.ja.length||(He(a.ha),a.ha=null))}
function dk(a){return{H:function(b,c){var d=b.D;if(d){var e=P(a).m("adBlockEnabled");e&&d.A("adb",e)}c()}}}function ek(a,b){var c=a.document;if(J(c.readyState,["interactive","complete"]))sg(a,b);else{var d=Hc(a),e=d.C,f=d.xa,g=function(){f(c,["DOMContentLoaded"],g);f(a,["load"],g);b()};e(c,["DOMContentLoaded"],g);e(a,["load"],g)}}
var fk=C("9-d5ve+.r%7",v),gk=X("ad",function(a,b){if(!b.Fa){var c=P(a);if(!c.m("adBlockEnabled")){var d=function(m){J(m,["2","1"])&&c.A("adBlockEnabled",m)},e=Ad(a),f=e.m("isad");if(f)d(f);else{var g=C("adStatus",c.A),h=function(m){m=m?"1":"2";d(m);g("complete");e.A("isad",m,1200);return m},k=ig(a,"adb",b);if(!c.m("adStatus")){g("process");var l="metrika/a"+fk().replace(/[^a-v]+/g,"")+"t.gif";ek(a,function(){return k({$:{U:l}}).then(C(!1,h))["catch"](C(!0,h))})}}}}}),hk=w(Cd);
function ik(a){var b=hk();b.Sc||(b.Sc=a)}C(ce("ccf"),zc);
function jk(a,b,c,d,e){if(b.qa&&b.ta&&(b.qa===a.qa&&b.ta===a.ta||M(a,b,{M:{},Ra:!0}),0<e&&Nd(a.T,[e]),K(function(f){var g=p(f);f=g.next().value;g=g.next().value;var h={},k={};M(a.M,(k[f]=(h[g]=+(a.M[f]&&a.M[f][g]?a.M[f][g]:0),h),k))},d),K(function(f){var g=p(f);f=g.next().value;g=g.next().value;var h={},k={};M(a.M,(k[f]=(h[g]=1+(a.M[f]?a.M[f][g]:0),h),k))},c),a.yb&&(a.Ra||c.length))){if(b=xg(a.l,a.ob))c={},b.params("__ym","phc",(c.clientId=a.qa,c.orderId=a.ta,c.service_id=a.Qb,c.phones=a.M,c.performance=
a.T,c));a.Ra=!1}}var kk=w(function(a,b,c){function d(k){return e(a,b,k)?h[k.Ka]&&h[k.Ka].Na:null}var e=c.Yc,f={},g=void 0===c.Ec?(f.href=!0,f.text=!0,f):c.Ec,h;return function(k){return new Q(function(l,m){k&&k.length||m();h=ai()(k);af(a)(Xe(C({M:[],T:0},l),function(){var n=U(a),u=n(T),r=g.href?ci(a,h):[],y=g.text?bi(a,h,a.document.body):[];l({M:nb(tb,ob(K(d,r.concat(y)))),T:n(T)-u})}))})}});
function lk(a,b,c){a=Xh(c.Ka);if("href"===c.Gb){var d=c.va;b=d.href;c=b.replace(a,c.ca);if(b!==c)return d.href=c,!0}else if((b=null===(d=c.va.textContent)||void 0===d?void 0:d.replace(a,c.ca))&&b!==c.va.textContent)return c.va.textContent=b,!0;return!1}var mk=w(te,Ca);
function nk(a,b,c){b=zd(a,void 0,b);b=mk(a,b.m("phc_settings")||"");var d=G(b,"clientId"),e=G(b,"orderId"),f=G(b,"service_id"),g=G(b,"phones")||[];return d&&e&&g&&f?kk(a,c.ob,{Yc:lk})(g).then(function(h){return jk(c,{qa:d,ta:e,Qb:f},h.M,g,h.T)})["catch"](t):Q.resolve()}
var ok=X("phc.p",function(a,b){if(!fi(a))return ng(b,function(c){var d=b.id,e=zd(a,void 0,d),f=e.m("phc_settings")||"";if(c=G(c,"settings.phchange")){var g=ue(a,c)||"";g!==f&&e.A("phc_settings",g)}else f&&(c=mk(a,f));e=G(c,"clientId");f=G(c,"orderId");c=G(c,"phones")||[];e&&f&&c.length&&(f={qa:"",ta:"",Qb:0,M:{},T:[],yb:!1,Ra:!0,l:a,ob:b},M(f,{yb:!0}),nk(a,d,f),c=bf(a),e=ei(a,c),d=Va(nk,null,a,d,f),e.C(d),di(a,c))})}),pk="architecture bitness model platformVersion uaFullVersion fullVersionList".split(" "),
qk=ed("uah",function(a){if(!ua("getHighEntropyValues",G(a,"navigator.userAgentData.getHighEntropyValues")))return Q.reject("0");try{return a.navigator.userAgentData.getHighEntropyValues(pk).then(function(b){if(!Ra(b))throw"2";return b},function(){throw"1";})}catch(b){return Q.reject("3")}}),rk=new RegExp(S("|","yandex.com/bots;Googlebot;APIs-Google;Mediapartners-Google;AdsBot-Google;FeedFetcher-Google;Google-Read-Aloud;DuplexWeb-Google;Google Favicon;googleweblight;Lighthouse;Mail.RU_Bot;StackRambler;Slurp;msnbot;bingbot;www.baidu.com/search/spi_?der.htm".split(";")).replace(/[./]/g,
"\\$&")),sk=w(function(a){var b=zb(a);return(b=rk.test(b))?Q.resolve(b):qk(a).then(function(c){try{return E(function(d,e){return d||rk.test(e.brand)},!1,c.brands)}catch(d){return!1}},C(!1,v))}),tk=["0","1","2","3"],uk=tk[0],vk=tk[1],wk=tk[2],xk=["GDPR-ok-view-detailed-0","GDPR-ok-view-detailed-1","GDPR-ok-view-detailed-2","GDPR-ok-view-detailed-3"],yk=["GDPR-ok-view-default","GDPR-ok-view-detailed"].concat(xk);
function zk(a){if(J(a,["GDPR-ok-view-default","GDPR-ok-view-detailed"]))return uk;a=a.replace("GDPR-ok-view-detailed-","");return J(a,tk)?a:uk}var Ak="GDPR-ok GDPR-cross GDPR-cancel 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 GDPR-settings GDPR-ok-view-default GDPR-ok-view-detailed 21 22 23".split(" ").concat(xk).concat(["28","29","30","31"]),Bk="3 13 14 31 15 16 17 28".split(" "),Ck=F(Fb(I("ymetrikaEvent.type")),pb(qb(Ak)));function Dk(a,b,c){a=c||ec(a);return J(a,b)?a:"en"}
var Ek={Cc:!0,url:"https://yastatic.net/s3/gdpr/v3/gdpr",Db:"",Ab:"az be en es et fi fr hy ka kk ky lt lv no pt ro ru sl tg tr uz cs da de el hr it nl pl sk sv".split(" ")},Fk=ed("gdpr",function(a,b,c,d,e){function f(n){b("10");c.C(yk,function(u){u=u.type;var r={};l.Lb((r.type=u,r));n({value:zk(u)})})}var g=void 0===e?Ek:e;e=g.url;var h=g.Db,k=g.Cc;g=Dk(a,g.Ab,d.dd);var l=$g(a,d);if(!l)return Q.resolve({value:uk,Wa:!0});if(a._yaGdprLoaded)return new Q(function(n){b("7");f(n)});var m=Lf(a,{src:""+
e+(k?"":g)+h+".js"});return new Q(function(n,u){m?(b("7"),m.onerror=function(){b("9");var r={};l.Lb((r.type="GDPR-ok-view-default",r));n(null)},m.onload=C(n,f)):(b("9"),u(ce("gdp.e")))})});function Gk(a,b){var c=$g(a,b);c&&c.ba.C(["isYandex"],function(){var d={};return d.type="isYandex",d.isYandex=hj(a),d})}
function Hk(a,b,c){var d=$g(a,c);return new Q(function(e){if(d){var f=d.ba,g=F(C("4",b),C(null,e)),h=We(a,g,2E3,"gdp.f.t"),k={};d.Nb((k.type="isYandex",k)).then(function(l){l.isYandex?(b("5"),f.C(yk,function(m){m=p(m);m.next();m=m.next().value.type;e({value:zk(m)})})):(b("6"),e(null))})["catch"](g).then(B([a,h],Ve))}else e({value:vk,Wa:!0})})}
var Ik={},Jk=(Ik["GDPR-ok"]="ok",Ik["GDPR-ok-view-default"]="ok-default",Ik["GDPR-ok-view-detailed"]="ok-detailed",Ik["GDPR-ok-view-detailed-0"]="ok-detailed-all",Ik["GDPR-ok-view-detailed-1"]="ok-detailed-tech",Ik["GDPR-ok-view-detailed-2"]="ok-detailed-tech-analytics",Ik["GDPR-ok-view-detailed-3"]="ok-detailed-tech-other",Ik);function Kk(a,b){if(hj(a)){var c=bh(a),d=xg(a,b);d=d&&d.params;c=K(C(Jk,G),Ck(c));d&&c.length&&d("gdpr",ob(c))}}
var Lk="az be en es et fi fr hy ka kk ky lt lv no pt ro ru sl tg tr uz ar he sr uk zh".split(" "),Mk=[],Nk=Wa("push",Mk),Ok=w(function(a,b){var c=b.m("gdpr");return J(c,tk)?"-"+c:""});
function Pk(a,b,c,d){if(!c.D||pc(b.L))d();else{var e=bh(a),f=C(e,ah),g=zd(a,""),h=function(){var u=S(",",K(Ba(Ak),Ck(e)));u=""+u+Ok(u,g);me(c,"gdpr",u);d()};if(b.cd)f("31"),h();else if(3===b.id)h();else{var k=P(a),l=k.m("f1");if(l)l(h);else if(l=Ck(e),Jb(qb(Ak),l))h();else if(g.m("yandex_login"))f("13"),g.A("gdpr",uk,525600),h();else{l=hj(a);var m=V(a);var n=/(^|\w+\.)yango(\.yandex)?\.com$/.test(m.hostname)?{url:"https://yastatic.net/s3/taxi-front/yango-gdpr-popup/",version:2,Ab:Lk,Db:"_inversed_buttons"}:
void 0;l||n?(l=g.m("gdpr"),J(l,tk)?(f(l===vk?"12":"3"),h()):oi(a)||pi(a)?(f("17"),h()):sk(a).then(v,t).then(function(u){u?(f("28"),h()):(Nk(h),k.A("f1",Nk),u=p(aj).next().value,u(a).then(I("params.eu")).then(function(r){if(r||Na(m.href,"yagdprcheck=1")||g.m("yaGdprCheck")){g.A("gdpr_popup",vk);Gk(a,b);if(fc(a))return Hk(a,f,b);var y=eh(a,e);if(y)return r=Fk(a,f,y,b,n),r.then(B([a,b],Kk)),r}r||f("8");return Q.resolve({value:uk,Wa:!0})}).then(function(r){g.Aa("gdpr_popup");if(r){var y=r.value;r=r.Wa;
J(y,tk)&&g.A("gdpr",y,r?void 0:525600)}y=Yc(Mk,Od);ui(a,y,20)(Xe(W(a,"gdr"),t));k.A("f1",Od)})["catch"](W(a,"gdp.a")))})):(f("14"),h())}}}}var Qk=nc.split("."),Rk=Qk.pop(),Sk=S(".",Qk),Tk={};function Uk(a){var b=Yj+"/tag_debug.js?ver="+N.ea+"&b=pp";Tk[b]||(Tk[b]={Mc:Lf(a,{src:b}),state:0});return Tk[b]}function Vk(a,b){function c(){e.state=1;b()}function d(){e.state=2}var e=Uk(a),f=e.Mc,g=e.state;f&&2!==g?1===g?c():(g=Hc(a),g.C(f,["load"],c),g.C(f,["error"],d)):d()}var Wk=w(Cd,O);
function Xk(a,b,c){var d=Wk(b).Jc;if(!d)throw xc("im.no");Vk(a,function(){var e=P(a).m("ytmm");(e=G(e,"tag_debug.init"))&&e(d,c,N.ea)})}var Yk=ed("csy",Cd);function Zk(a,b,c){a=Yk(a);var d=a[b];d||(d=[],a[b]=d);10>d.length&&d.push(c)}function $k(a,b,c){a=Yk(a)[b];c&&a&&c.A("cs",S("",a))}var al=w(Dd);function bl(a){a=ec(a);return Qi[a]||"ru"}function cl(a){a=ej(a);return Ni[a]||a}
var dl=w(function(){var a=E(function(b,c){"ru"!==c&&(b[c]=Sk+"."+c);return b},{},id);K(function(b){a[b]=b},L(Oi));return a}),el=w(function(a){a=V(a).hostname;return(a=Hd(F(I("1"),bb("test"),na(Od)(a)),Qb(Oi)))&&a[0]});function fl(a,b){var c=bl(a),d=[el(a)||cl(a)];fj(a)&&d.push(c);var e=U(a);c=Be(a);var f=c.m("synced",{});d=nb(function(g){if(b[g]){var h=(f[g]||1)+1440<e(Nc);h&&delete f[g];return h}},d);c.A("synced",f);return K(function(g){return{Rc:b[g],Dc:g}},d)}var gl=0,hl=[],il=t;
function jl(a,b,c,d,e,f){f=void 0===f?t:f;Ve(a,gl);var g=Be(a),h=a=U(a)(Nc);e?f("9"):(f("8"),h=a-1435);var k=g.m("synced")||{};K(function(l){k[l.Dc]=h},d);g.A("synced",k);il();ck(b);hl=[];c()}
function kl(a,b,c,d,e,f,g){f=void 0===f?t:f;var h=G(g,"data");if(Ia(h)){var k=p(h.split("*"));h=k.next().value;var l=k.next().value;k=k.next().value;if("sc.image"===h&&l){J(l,hl)&&(f("a"),e.A("startSync",!1),e=al(a),K(Od,e),xb(e),hl=nb(F(pa(l),Da),hl));if("1"!==k){f("b"+k);jl(a,b,c,d,!1);return}f("d")}if("sc.image"===h||"sc.frame"===h)hl.length?(f("c"),g.source.postMessage("sc.images*"+hl[0],"*")):jl(a,b,c,d,!0)}else f("7")}
var ll=function(a,b){return function(c,d){if(jc(c)||Bb(c))return{};var e=O(d),f=dl(e),g=fl(c,f),h=B([c,e],Zk),k=P(c),l=fc(c);return{H:function(m,n){var u=m.D,r=F(B([c,e,m.V],$k),n),y=fj(c);y||h("0");l&&h("1");(u=!(u&&u.m("pv")))&&h("2");if(!y||l||u)return r();if(!g.length)return h("3"),r();if(k.m("startSync"))y=al(c),h("4"),y.push(r);else{k.A("startSync",!0);y=B([c,g,d.id,h,!1],a);u=p(aj).next().value;if(!u)return h("h"),r();h("j");u(c).then(y).then(r,F(qa(r),W(c,b)))["catch"](t)}}}}}(function(a,
b,c,d,e){d=void 0===d?t:d;return new Q(function(f,g){var h=Vj()+Vj()+"-"+Vj()+"-"+Vj()+"-"+Vj()+"-"+Vj()+Vj()+Vj();ik(h);var k={},l=cd((k.scid=h,k.cid=c,k));hl=K(function(m){return N.fa+"//"+m.Rc+"/sync_cookie_image_check"+(e?"_secondary":"")+"?"+l},b);hl.length?bk(a)?(h=Hc(a),k=P(a),il=h.C(a,["message"],B([a,Zj,f,b,k,d],kl)),gl=We(a,B([a,Zj,f,b,!1,d],jl),1500)):(d("6"),g()):(d("3"),f())})},"sy.c.f"),ml={},nl=(ml.brands="chu",ml.architecture="cha",ml.bitness="chb",ml.uaFullVersion="chf",ml.fullVersionList=
"chl",ml.mobile="chm",ml.model="cho",ml.platform="chp",ml.platformVersion="chv",ml);function ol(a){return Ia(a)?a:tb(a)?S(",",K(function(b){return'"'+b.brand+'";v="'+b.version+'"'},a)):Qa(a)?"":a?"?1":"?0"}function pl(a){return"che\n"+a}function ql(a){var b=E(function(c,d){var e=p(d),f=e.next().value;e=e.next().value;(f=ol(a[f]))&&c.push(""+e+"\n"+f);return c},[],Qb(nl));return S("\n",b)}var rl=w(function(a){return qk(a).then(ql,pl)});
function sl(a){return{H:function(b,c){rl(a).then(function(d){b.B||(b.B={});b.B.uah=d;c()},c)}}}function tl(a,b){if("https://oauth.yandex.ru"===G(b,"origin")&&G(b,"source.window")&&"_ym_uid_request"===G(b.data,"_ym")){var c=b.source,d={};d=(d._ym_uid=a,d);c.postMessage(d,"https://oauth.yandex.ru")}}
var ul=ed("ot",function(a,b){if(lc(a)){var c=Hc(a);return ng(b,W(a,"ot.s",function(d){if(G(d,"settings.oauth")){var e=[],f=mf(a,b);e.push(c.C(a,["message"],W(a,"ot.m",C(f,tl))));af(a)(Xe(t,W(a,"ot.b",function(){function g(n){var u=n.href;if(u&&Fg(u,"https://oauth.yandex.ru/")&&!Na(u,"_ym_uid=")){u=Na(u,"?")?"&":"?";var r={};n.href+=""+u+cd((r._ym_uid=f,r.mc="v",r));c.C(n,["click"],W(a,"ot.click",function(){var y="et="+k(T);n.href+="&"+y}))}}var h=a.document.body,k=U(a),l=yh("a",h);K(g,l);if(ua("MutationObserver",
a.MutationObserver)){l=new a.MutationObserver(W(a,"ot.m",C(function(n){n=n.addedNodes;for(var u=0;u<n.length;u+=1){var r=n[u];"A"===r.nodeName&&g(r)}},K)));var m={};m=(m.childList=!0,m.subtree=!0,m);l.observe(h,m);e.push(Va(l.disconnect,l))}})));return B([Pd,e],K)}}))}}),vl=X("p.cm",function(a){tc(a).O("mcs",X("p.cm.cs",function(b,c,d,e,f){if(xg(a,c))return Qj(b,c,d,e,f);zc(xc("cmws.cd"))})).O("wsfm",uf)}),wl=X("destruct.e",function(a,b,c){return function(){var d=P(a),e=b.id;K(function(f,g){return x(f)&&
W(a,"dest.fr."+g,f)()},c);delete d.m("counters")[O(b)];delete a["yaCounter"+e]}});function xl(a,b,c,d){return function(){var e=Ga(arguments);e=d.apply(null,da(e));return z(e)?xg(a,b):e}}function yl(a,b,c,d){return W(a,"cm."+c,d)}function zl(a,b,c,d,e){if(!c.length)return e;c=K(function(f){return B([a,b,d],f)},c);return F.apply(null,da(c))(e)}var Al=P(window);Al.O("hitParam",{});P(window).O("getCounters",Mg(window));Ag.push(Ng);hg["1"]=$d;Bg.push(Wg);dg["1"]=$f;Hf(Sg,-1);
Jf["1"]=[[Sg,-1],[be,1],[Bf,2],[uf(),3],[Ef,4]];Bg.push(gh);
Bg.push(X("p.ar",function(a,b){var c=ig(a,"a",b),d={};return d.hit=function(e,f,g,h,k,l){var m={};m={B:{},D:Jd((m.pv=1,m.ar=1,m))};f=Ra(f)?{title:f.title,Fb:f.referer,G:f.params,za:f.callback,l:f.ctx}:{title:f,Fb:g,G:h,za:k,l:l};h=Ug(b);g=e||V(a).href;h.url!==g&&(h.ref=h.url,h.url=e);e=f.Fb||h.ref||a.document.referrer;h={};h=rg(a,b,"pv",(h.id=b.id,h.url=g,h.ref=e,h),f.G);k=M(m.F||{},{G:f.G,title:f.title});l={};m=c(M(m,{F:k,B:M(m.B||{},(l["page-url"]=g,l["page-ref"]=e,l))}),b).then(h);return Tg(a,
"p.ar.s",m,f.za||t,f.l)},d}));hg.a=$d;Jf.a=Ff;dg.a=$f;Bg.push(jh);hg.g=$d;dg.g=$f;Jf.g=Ff;
Bg.push(X("cl.p",function(a,b){function c(n,u,r,y){y=void 0===y?{}:y;r?mh(a,b,{url:r,ia:!0,Ba:n,Ga:u,sender:d,Zb:y}):g.warn("clel")}var d=ig(a,"2",b),e=[],f=O(b),g=pg(a,f),h=W(a,"s.s.tr",C(Kg(a,f),lh));f={l:a,sa:b,sc:e,sender:d,kd:P(a),qc:Ce(a,b.id),md:Qe(a),Xc:C(C(f,Lg(a)),F(Od,I("trackLinks")))};f=W(a,"cl.p.c",C(f,nh));f=Hc(a).C(a,["click"],f);b.Vb&&h(b.Vb);var k=W(a,"file.clc",B([!0,!1],c)),l=W(a,"e.l.l.clc",B([!1,!0],c));e=W(a,"add.f.e.clc",oh(e));var m={};return m.file=k,m.extLink=l,m.addFileExtension=
e,m.trackLinks=h,m.u=f,m}));Jf["2"]=Ff;hg["2"]=$d;dg["2"]=$f;hg.r=Zd("r");dg.r=["f","x","j","i"];Cg.push(X("p.r",function(a,b){var c=uh(a),d=ig(a,"r",b),e=W(a,"rts.p");return ng(b,B([function(f,g){var h={id:g.pc,L:g.L},k={I:{K:g.Hc},D:Jd(g.kc),B:g.G,F:{wa:g.wa},$:{U:g.U}};g.V&&(k.V=le(g.V));h=d(k,h)["catch"](e);return f.then(C(h,v))},Q.resolve(),c],E)).then(C(void 0,v))["catch"](e)}));
Z("r",function(a){return{H:function(b,c){var d=void 0===b.D?Jd():b.D,e=b.F.wa,f=ph(a),g=d.m("rqnl",0)+1;d.A("rqnl",g);if(d=G(f,S(".",[e,"browserInfo"])))d.rqnl=g,qh(a);c()},da:function(b,c){rh(a,b);c()}}},1);Hf(sh,100);Z("1",sh,100);Z("n",sh,100);Bg.push(wh);Z("n",be,1);Z("n",Bf,2);Z("n",uf(),3);Z("n",Ef,3);hg.n=$d;dg.n=$f;M(sc,{mb:{X:"accurateTrackBounce"}});Bg.push(Uh);ne.push("ecommerce");M(sc,{pb:{X:"ecommerce",bb:function(a){if(a)return!0===a?"dataLayer":""+a}}});qd.push("_ym_debug");Eg.unshift(ji);
var Bl={},Cl=(Bl.tp=F(Ca,Qg,ib),Bl.tpid=F(Ca,function(a){a=O(a);return Og[a]&&Og[a].Wc||null}),Bl);M(sf,Cl);Hf(ki,20);Z("n",ki,20);Z("1",ki,20);Eg.unshift(mi);
sf.fp=function(a,b,c){if(c.B&&c.B.nohit)return null;c=P(a).m;if(!c("fpe"))return null;b=li(b);if(b.uc)return null;c=c("fht",Infinity);a:{var d=G(a,"performance.getEntriesByType");if(x(d)){if(a=nb(F(v,I("name"),pa("first-contentful-paint")),d.call(a.performance,"paint")),a.length){a=a[0].startTime;break a}}else{var e=G(a,"chrome.loadTimes");d=qf(a);if(x(e)&&(e=e.call(a.chrome),e=G(e,"firstPaintTime"),d&&e)){a=1E3*e-d;break a}if(a=G(a,"performance.timing.msFirstPaint")){a-=d;break a}}a=void 0}return a&&
c>a?(b.uc=a,Math.round(a)):null};M(sf,{bu:yi,ds:function(a,b,c){if((void 0===c.B?{}:c.B).nohit)return null;a=Ic(a);if(!a)return null;var d=c=null;G(a,"getEntriesByType")&&(d=G(a.getEntriesByType("navigation"),"0"))&&(c=Ai);if(!c){var e=G(a,"timing");e&&(c=zi,d=e)}if(!c)return null;a=Ei(a,d,c);b=O(b);b=Di(b);return(b=Fi(b,a))&&S(",",b)},td:function(a){return P(a).m("tpuid")}});
(function(){var a={};a.oo=wi("oo");a.yu=function(b){return(b=zd(b,"").m("yandexuid"))&&b.substring(0,25)};a.ecs=wi("ecs");a.pe=C(1,v);a.cdl=wi("cdl");a.eco=w(Ri,F(Ca,O));a.dss=wi("dSync");M(se,a)})();dg.er=bg;(function(){var a=window;try{var b=eg(a,"er"),c=Xi(a,b);fe.push(function(d,e,f,g){var h={},k={},l={},m={},n={};c((n[d]=(m[N.ea]=(l[e]=(k[f]=g?(h[a.location.href]=g,h):a.location.href,k),l),m),n))})}catch(d){}})();
zg.push(function(a,b){if(G(a,"disableYaCounter"+b.id)||G(a,"Ya.disableMetrica")){var c=O(b);delete P(a).m("counters",{})[c];zc(ce("oo.e"))}});Gf.unshift(function(a){return{H:function(b,c){P(a).m("oo")||c()}}});Hf(function(a,b){return{H:function(c,d){var e=c.B,f=c.D;!Yi[b.id]&&f.m("pv")&&b.exp&&!e.nohit&&(e.exp=b.exp,Yi[b.id]=!0);d()}}},-99);Bg.push(Zi);Jf.e=Ff;hg.e=$d;dg.e=$f;M(sc,{exp:{X:"experiments"}});re.experiments="ex";Ag.push($i);
Hf(function(a){return{H:function(b,c){b.F&&b.F.G&&xi(a,b.F.G);c()}}},2.5);aj.push(bj);hg.f=$d;var Dl={};M(dg,(Dl.f=ag,Dl));Z("f",uf(),1);Z("f",vf,2);Z("f",ki,20);var El=["x"],Fl={};M(dg,(Fl.s=El,Fl.S=El,Fl.u=bg,Fl));var Gl={};M(hg,(Gl.s=Md,Gl.S=$d,Gl.u=Md,Gl));Z("s");Z("u");Z("S",uf(["v","hid","u","vf","rn"]),1);
Bg.push(X("s",function(a,b){return ng(b,function(c){var d=P(a),e=d.m,f=C("dSync",d.A);O(b);if(e("dSync",!1))f(1);else return f(!0),rj(a,c,{sa:b,Ic:"s",Cb:"ds",na:f,Tb:function(g,h,k){var l=g.Jb;g=g.host;if(G(l,"settings"))return zc(ce("ds.e"));h=h(T)-k;k=g[1];g={};l=Jd((g.di=l,g.dit=h,g.dip=k,g));h={};h=(h["page-url"]=V(a).href,h);return ig(a,"S",Li)({D:l,B:h},Li).then(C(10,f),W(a,"ds.rs"))}})})}));Cg.push(Tj);Hf(dk,6);Z("1",dk,6);Z("adb");Z("n",dk,4);dg.adb=bg;hg.adb=Yd;Ag.push(gk);hg.d=$d;
Z("d",uf(["hid","u","v","vf"]),1);dg.d=bg;
Z("n",function(a,b){return{da:function(c,d){if(!c.F||!c.F.force){var e=b.id===N.hc?1:.002,f=.002;f=void 0===f?1:f;e=void 0===e?1:e;var g=Ic(a);if(g&&x(g.getEntriesByType)){f=Math.random()>f;var h=Math.random()>e;if(!f||!h){var k=g.getEntriesByType("resource"),l={},m={};g={};var n=Ui();e=V(a).href;for(var u=0;u<k.length;u+=1){var r=k[u],y=p(r.name.replace(Si,"").split("?")).next().value,A=Bh(y),H={};H=(H.dns=Math.round(r.domainLookupEnd-r.domainLookupStart),H.tcp=Math.round(r.connectEnd-r.connectStart),
H.duration=Math.round(r.duration),H.response=Math.round(r.responseEnd-r.requestStart),H);if("script"===r.initiatorType&&!f){var D={};m[y]=M(H,(D.name=r.name,D.decodedBodySize=r.decodedBodySize,D.transferSize=Math.round(r.transferSize),D))}!Ti[A]&&!n[A]||l[y]||h||(r={},l[y]=M(H,(r.pages=e,r)))}L(l).length&&(g.timings8=l);L(m).length&&(g.scripts=m);L(g).length&&(f={},h={},ig(a,"d",b)({D:Jd((f.ar=1,f.pv=1,f)),I:{K:ue(a,g)||void 0},B:(h["page-url"]=e,h)},{id:N.jc,L:"0"})["catch"](W(a,"r.tim.ng2")))}}}d()}}},
7);Bg.push(ok);Ag.push(Xj);M(sc,{cd:{X:"yaDisableGDPR"},dd:{X:"yaGDPRLang"}});Gf.push(function(a,b){return{H:B([a,b],Pk)}});qd.push("gdpr");qd.push("gdpr_popup");rd.push(function(a,b){var c=bh(a);c=Ck(c);if(nb(qb(Bk),c).length)return!0;c=b(a,"gdpr");return J(c,[uk,wk])});
Gf.push(function(a){return{H:function(b,c){var d=b.$||{},e;if(e=G(a,"document.referrer")){b:{if(e=Nf(a,e).host.match(jd)){var f=p(e);f.next();e=f.next().value;if(f=f.next().value){e=J(f,id)?f:!1;break b}if(e){e=id[0];break b}}e=!1}e=Sk+"."+(e||Rk)}else e=nc;b.$=M(d,{ub:[e]});c()}}});Hf(ll,5);Z("1",ll,6);dg.c=bg;hg.c=Md;Z("h",sl,7);Z("1",sl,7);Hf(sl,7);Cg.push(X("p.ot",ul));
Eg.push(X("cdl",function(a){var b=P(a).O;if(a=G(a,"navigator.cookieDeprecationLabel"))try{a.getValue().then(C("cdl",b),B(["cdl","e"],b))}catch(c){b("cdl","d")}else b("cdl","na")}));Bg.push(vl);Cg.unshift(function(a,b){ng(b,function(c){var d=Bd(a),e=G(c,"settings.sm"),f=gi(a);(d||e||f.id)&&Xk(a,b,c)})});
function Hl(a,b,c,d){var e=this;return W(window,"c.i",function(){function f(A){(A=Ch(k,m,"",A)(k,m))&&(x(A.then)?A.then(g):g(A));return A}function g(A){A&&(x(A)?n.push(A):Ra(A)&&K(function(H){var D=p(H);H=D.next().value;D=D.next().value;x(D)&&("u"===H?n.push(D):h(D,H))},Qb(A)))}function h(A,H,D){e[H]=zl(k,m,D||u,H,A)}var k=window;(!k||isNaN(a)&&!a)&&de();var l=qc(a,b,c,d),m=rc(l);Wk(m).Jc=l;Pg(m,m.G||{});var n=[],u=[yl,Ch,xl];u.unshift(yg);var r=K(v,Cg);l=O(m);m.id||zc(xc("Invalid Metrika id: "+m.id,
!0));var y=Al.m("counters",{});if(y[l])return r={},qg(k,l,"dc",(r.key=l,r)),y[l];y[l]=e;Al.A("counters",y);Al.O("counter",e);K(function(A){A(k,m)},zg);K(f,Ag);f(tg);h(wl(k,m,n),"destruct",[yl,xl]);sg(k,B([k,r,f,1,"a.i"],Uj));K(f,Bg);l={};Fd(k,(l.counterKey=O(m),l.name="counter",l.data=Ud(m),l))})()}K(na(Od)(window),Eg);if(window.Ya&&Hl){var Il=N.nc;window.Ya[Il]=Hl;wg(window);K(F(ab([window,window.Ya[Il]]),Od),Dg)};}).call(this);
